///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace G4_TEST_POST_RILASCIO._01__AvvioProgramma
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoginG4 recording.
    /// </summary>
    [TestModule("af64ae32-1c52-4945-a637-91b69c1d36dd", ModuleType.Recording, 1)]
    public partial class LoginG4 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::G4_TEST_POST_RILASCIO.G4_TEST_POST_RILASCIORepository repository.
        /// </summary>
        public static global::G4_TEST_POST_RILASCIO.G4_TEST_POST_RILASCIORepository repo = global::G4_TEST_POST_RILASCIO.G4_TEST_POST_RILASCIORepository.Instance;

        static LoginG4 instance = new LoginG4();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoginG4()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoginG4 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 5m to exist. Associated repository item: 'ApplicationUnderTest.Login.SchermataLogin'", repo.ApplicationUnderTest.Login.SchermataLoginInfo, new ActionTimeout(300000), new RecordItemIndex(0));
            repo.ApplicationUnderTest.Login.SchermataLoginInfo.WaitForExists(300000);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Utente01' with focus on 'ApplicationUnderTest.Login.Password'.", repo.ApplicationUnderTest.Login.PasswordInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Login.Password.PressKeys("Utente01");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Login.Accedi' at 21;12.", repo.ApplicationUnderTest.Login.AccediInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Login.Accedi.Click("21;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 3m to exist. Associated repository item: 'ApplicationUnderTest.Login.DataControlloCredito'", repo.ApplicationUnderTest.Login.DataControlloCreditoInfo, new ActionTimeout(180000), new RecordItemIndex(3));
            repo.ApplicationUnderTest.Login.DataControlloCreditoInfo.WaitForExists(180000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
