///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace G4_TEST_POST_RILASCIO._02__Ispezione
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AvviaIspezione recording.
    /// </summary>
    [TestModule("a474be47-8b84-40e7-ad50-a7b2ab527e78", ModuleType.Recording, 1)]
    public partial class AvviaIspezione : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::G4_TEST_POST_RILASCIO.G4_TEST_POST_RILASCIORepository repository.
        /// </summary>
        public static global::G4_TEST_POST_RILASCIO.G4_TEST_POST_RILASCIORepository repo = global::G4_TEST_POST_RILASCIO.G4_TEST_POST_RILASCIORepository.Instance;

        static AvviaIspezione instance = new AvviaIspezione();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AvviaIspezione()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AvviaIspezione Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Tile_Ispezione' at 209;27.", repo.ApplicationUnderTest.Tile_IspezioneInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Tile_Ispezione.Click("209;27");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
