///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace G4_TEST_POST_RILASCIO._02__Ispezione
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InvioAllaLinea recording.
    /// </summary>
    [TestModule("8e8dbf75-e6a1-42b0-95ba-46839017b641", ModuleType.Recording, 1)]
    public partial class InvioAllaLinea : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::G4_TEST_POST_RILASCIO.G4_TEST_POST_RILASCIORepository repository.
        /// </summary>
        public static global::G4_TEST_POST_RILASCIO.G4_TEST_POST_RILASCIORepository repo = global::G4_TEST_POST_RILASCIO.G4_TEST_POST_RILASCIORepository.Instance;

        static InvioAllaLinea instance = new InvioAllaLinea();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InvioAllaLinea()
        {
            EndRevisione = "0";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InvioAllaLinea Instance
        {
            get { return instance; }
        }

#region Variables

        string _EndRevisione;

        /// <summary>
        /// Gets or sets the value of variable EndRevisione.
        /// </summary>
        [TestVariable("8b8498ae-b039-45f3-9ec5-c3a2c39c79f4")]
        public string EndRevisione
        {
            get { return _EndRevisione; }
            set { _EndRevisione = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Invio la PC stazione
            Report.Log(ReportLevel.Info, "Mouse", "Invio la PC stazione\r\nMouse Left Click item 'ApplicationUnderTest.RootGrid.Ispezione_InviaPCStazione' at Center.", repo.ApplicationUnderTest.RootGrid.Ispezione_InviaPCStazioneInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.RootGrid.Ispezione_InviaPCStazione.Click();
            Delay.Milliseconds(200);
            
            IncrementEndIspezione();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
