///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace G4_TEST_POST_RILASCIO._02__Ispezione
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NuovaIspezioneGenerica recording.
    /// </summary>
    [TestModule("9e13677e-7374-42fb-a36d-ce1f0f0d7f16", ModuleType.Recording, 1)]
    public partial class NuovaIspezioneGenerica : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::G4_TEST_POST_RILASCIO.G4_TEST_POST_RILASCIORepository repository.
        /// </summary>
        public static global::G4_TEST_POST_RILASCIO.G4_TEST_POST_RILASCIORepository repo = global::G4_TEST_POST_RILASCIO.G4_TEST_POST_RILASCIORepository.Instance;

        static NuovaIspezioneGenerica instance = new NuovaIspezioneGenerica();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NuovaIspezioneGenerica()
        {
            TESTA = "";
            InArchivio = "";
            Categoria = "";
            CIC = "";
            Targa = "";
            Telaio = "";
            KM = "";
            Omologazione = "";
            Marca = "";
            Modello = "";
            N_Posti = "";
            Data_Imm = "";
            RilascioCarta = "";
            Committente = "";
            N1Alimentazione = "";
            N2Alimentazione = "";
            DiFabbrica = "";
            TipoMotore = "";
            Tempi = "";
            N_Cilindri = "";
            Cilindrata = "";
            TipoCambio = "";
            Pt_CV = "";
            Pt_KW = "";
            Scad_Imp_GPLMet = "";
            Tara = "";
            MassaMassima = "";
            Traino = "";
            MassaRim = "";
            MaxDB = "";
            GiriMotoreDB = "";
            GiriMax = "";
            LimiteGiri = "";
            Dir_Emiss_Scarico = "";
            Direttiva_Acustica = "";
            Dir_Avvio_Acustico = "";
            Limiti_Lambda_Min = "";
            Limiti_Lambda_Max = "";
            Limite_K = "";
            N_Scarichiq = "";
            N30cm = "";
            Alt_Anab = "";
            Tipo_Faro_UnicoSx = "";
            N_Fari = "";
            Tipo_Faro_DX = "";
            Az_Servizio = "";
            Schema_Soccorso = "";
            Az_Stazio_____namento = "";
            Imp_Servizio = "";
            Imp_Soccorso = "";
            Imp_Stazio_____namento = "";
            N4x4 = "";
            N_Assi = "";
            Posizione_Asse_Staz = "";
            ABS = "";
            RuotaSingola = "";
            Inserimento_Misura_Guidato_1 = "";
            Inserimento_Misura_Guidato_2 = "";
            Inserimento_Misura_Guidato_3 = "";
            Inserimento_Misura_Guidato_4 = "";
            Inserimento_Misura_Guidato_5 = "";
            Inserimento_Misura_Guidato_Diretto = "";
            Tipo = "";
            Cognome = "";
            Nome = "";
            Comune = "";
            Localita = "";
            Provincia = "";
            Tipo_Strada = "";
            Nome_Strada = "";
            Num_ = "";
            Cap = "";
            Comune_Nascita = "";
            Nato_Estero = "";
            Data_Nascita = "";
            Sesso = "";
            Invio_Richiamo = "";
            Preferenza = "";
            Fisso = "";
            Cellulare = "";
            Fax = "";
            Mail = "";
            Categoria_Anagrafica = "";
            P_Iva = "";
            Cod_Fiscale = "";
            Doc_Identita_Patente = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NuovaIspezioneGenerica Instance
        {
            get { return instance; }
        }

#region Variables

        string _TESTA;

        /// <summary>
        /// Gets or sets the value of variable TESTA.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e10")]
        public string TESTA
        {
            get { return _TESTA; }
            set { _TESTA = value; }
        }

        string _InArchivio;

        /// <summary>
        /// Gets or sets the value of variable InArchivio.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e11")]
        public string InArchivio
        {
            get { return _InArchivio; }
            set { _InArchivio = value; }
        }

        string _Categoria;

        /// <summary>
        /// Gets or sets the value of variable Categoria.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e12")]
        public string Categoria
        {
            get { return _Categoria; }
            set { _Categoria = value; }
        }

        string _CIC;

        /// <summary>
        /// Gets or sets the value of variable CIC.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e13")]
        public string CIC
        {
            get { return _CIC; }
            set { _CIC = value; }
        }

        string _Targa;

        /// <summary>
        /// Gets or sets the value of variable Targa.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e14")]
        public string Targa
        {
            get { return _Targa; }
            set { _Targa = value; }
        }

        string _Telaio;

        /// <summary>
        /// Gets or sets the value of variable Telaio.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e15")]
        public string Telaio
        {
            get { return _Telaio; }
            set { _Telaio = value; }
        }

        string _KM;

        /// <summary>
        /// Gets or sets the value of variable KM.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e16")]
        public string KM
        {
            get { return _KM; }
            set { _KM = value; }
        }

        string _Omologazione;

        /// <summary>
        /// Gets or sets the value of variable Omologazione.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e17")]
        public string Omologazione
        {
            get { return _Omologazione; }
            set { _Omologazione = value; }
        }

        string _Marca;

        /// <summary>
        /// Gets or sets the value of variable Marca.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e18")]
        public string Marca
        {
            get { return _Marca; }
            set { _Marca = value; }
        }

        string _Modello;

        /// <summary>
        /// Gets or sets the value of variable Modello.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e19")]
        public string Modello
        {
            get { return _Modello; }
            set { _Modello = value; }
        }

        string _N_Posti;

        /// <summary>
        /// Gets or sets the value of variable N_Posti.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e20")]
        public string N_Posti
        {
            get { return _N_Posti; }
            set { _N_Posti = value; }
        }

        string _Data_Imm;

        /// <summary>
        /// Gets or sets the value of variable Data_Imm.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e21")]
        public string Data_Imm
        {
            get { return _Data_Imm; }
            set { _Data_Imm = value; }
        }

        string _RilascioCarta;

        /// <summary>
        /// Gets or sets the value of variable RilascioCarta.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e22")]
        public string RilascioCarta
        {
            get { return _RilascioCarta; }
            set { _RilascioCarta = value; }
        }

        string _Committente;

        /// <summary>
        /// Gets or sets the value of variable Committente.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e23")]
        public string Committente
        {
            get { return _Committente; }
            set { _Committente = value; }
        }

        string _N1Alimentazione;

        /// <summary>
        /// Gets or sets the value of variable N1Alimentazione.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e24")]
        public string N1Alimentazione
        {
            get { return _N1Alimentazione; }
            set { _N1Alimentazione = value; }
        }

        string _N2Alimentazione;

        /// <summary>
        /// Gets or sets the value of variable N2Alimentazione.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e25")]
        public string N2Alimentazione
        {
            get { return _N2Alimentazione; }
            set { _N2Alimentazione = value; }
        }

        string _DiFabbrica;

        /// <summary>
        /// Gets or sets the value of variable DiFabbrica.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e26")]
        public string DiFabbrica
        {
            get { return _DiFabbrica; }
            set { _DiFabbrica = value; }
        }

        string _TipoMotore;

        /// <summary>
        /// Gets or sets the value of variable TipoMotore.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e27")]
        public string TipoMotore
        {
            get { return _TipoMotore; }
            set { _TipoMotore = value; }
        }

        string _Tempi;

        /// <summary>
        /// Gets or sets the value of variable Tempi.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e28")]
        public string Tempi
        {
            get { return _Tempi; }
            set { _Tempi = value; }
        }

        string _N_Cilindri;

        /// <summary>
        /// Gets or sets the value of variable N_Cilindri.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e29")]
        public string N_Cilindri
        {
            get { return _N_Cilindri; }
            set { _N_Cilindri = value; }
        }

        string _Cilindrata;

        /// <summary>
        /// Gets or sets the value of variable Cilindrata.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e30")]
        public string Cilindrata
        {
            get { return _Cilindrata; }
            set { _Cilindrata = value; }
        }

        string _TipoCambio;

        /// <summary>
        /// Gets or sets the value of variable TipoCambio.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e31")]
        public string TipoCambio
        {
            get { return _TipoCambio; }
            set { _TipoCambio = value; }
        }

        string _Pt_CV;

        /// <summary>
        /// Gets or sets the value of variable Pt_CV.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e32")]
        public string Pt_CV
        {
            get { return _Pt_CV; }
            set { _Pt_CV = value; }
        }

        string _Pt_KW;

        /// <summary>
        /// Gets or sets the value of variable Pt_KW.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e33")]
        public string Pt_KW
        {
            get { return _Pt_KW; }
            set { _Pt_KW = value; }
        }

        string _Scad_Imp_GPLMet;

        /// <summary>
        /// Gets or sets the value of variable Scad_Imp_GPLMet.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e34")]
        public string Scad_Imp_GPLMet
        {
            get { return _Scad_Imp_GPLMet; }
            set { _Scad_Imp_GPLMet = value; }
        }

        string _Tara;

        /// <summary>
        /// Gets or sets the value of variable Tara.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e35")]
        public string Tara
        {
            get { return _Tara; }
            set { _Tara = value; }
        }

        string _MassaMassima;

        /// <summary>
        /// Gets or sets the value of variable MassaMassima.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e36")]
        public string MassaMassima
        {
            get { return _MassaMassima; }
            set { _MassaMassima = value; }
        }

        string _Traino;

        /// <summary>
        /// Gets or sets the value of variable Traino.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e37")]
        public string Traino
        {
            get { return _Traino; }
            set { _Traino = value; }
        }

        string _MassaRim;

        /// <summary>
        /// Gets or sets the value of variable MassaRim.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e38")]
        public string MassaRim
        {
            get { return _MassaRim; }
            set { _MassaRim = value; }
        }

        string _MaxDB;

        /// <summary>
        /// Gets or sets the value of variable MaxDB.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e39")]
        public string MaxDB
        {
            get { return _MaxDB; }
            set { _MaxDB = value; }
        }

        string _GiriMotoreDB;

        /// <summary>
        /// Gets or sets the value of variable GiriMotoreDB.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e40")]
        public string GiriMotoreDB
        {
            get { return _GiriMotoreDB; }
            set { _GiriMotoreDB = value; }
        }

        string _GiriMax;

        /// <summary>
        /// Gets or sets the value of variable GiriMax.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e41")]
        public string GiriMax
        {
            get { return _GiriMax; }
            set { _GiriMax = value; }
        }

        string _LimiteGiri;

        /// <summary>
        /// Gets or sets the value of variable LimiteGiri.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e42")]
        public string LimiteGiri
        {
            get { return _LimiteGiri; }
            set { _LimiteGiri = value; }
        }

        string _Dir_Emiss_Scarico;

        /// <summary>
        /// Gets or sets the value of variable Dir_Emiss_Scarico.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e43")]
        public string Dir_Emiss_Scarico
        {
            get { return _Dir_Emiss_Scarico; }
            set { _Dir_Emiss_Scarico = value; }
        }

        string _Direttiva_Acustica;

        /// <summary>
        /// Gets or sets the value of variable Direttiva_Acustica.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e44")]
        public string Direttiva_Acustica
        {
            get { return _Direttiva_Acustica; }
            set { _Direttiva_Acustica = value; }
        }

        string _Dir_Avvio_Acustico;

        /// <summary>
        /// Gets or sets the value of variable Dir_Avvio_Acustico.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e45")]
        public string Dir_Avvio_Acustico
        {
            get { return _Dir_Avvio_Acustico; }
            set { _Dir_Avvio_Acustico = value; }
        }

        string _Limiti_Lambda_Min;

        /// <summary>
        /// Gets or sets the value of variable Limiti_Lambda_Min.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e46")]
        public string Limiti_Lambda_Min
        {
            get { return _Limiti_Lambda_Min; }
            set { _Limiti_Lambda_Min = value; }
        }

        string _Limiti_Lambda_Max;

        /// <summary>
        /// Gets or sets the value of variable Limiti_Lambda_Max.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e47")]
        public string Limiti_Lambda_Max
        {
            get { return _Limiti_Lambda_Max; }
            set { _Limiti_Lambda_Max = value; }
        }

        string _Limite_K;

        /// <summary>
        /// Gets or sets the value of variable Limite_K.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e48")]
        public string Limite_K
        {
            get { return _Limite_K; }
            set { _Limite_K = value; }
        }

        string _N_Scarichiq;

        /// <summary>
        /// Gets or sets the value of variable N_Scarichiq.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e49")]
        public string N_Scarichiq
        {
            get { return _N_Scarichiq; }
            set { _N_Scarichiq = value; }
        }

        string _N30cm;

        /// <summary>
        /// Gets or sets the value of variable N30cm.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e50")]
        public string N30cm
        {
            get { return _N30cm; }
            set { _N30cm = value; }
        }

        string _Alt_Anab;

        /// <summary>
        /// Gets or sets the value of variable Alt_Anab.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e51")]
        public string Alt_Anab
        {
            get { return _Alt_Anab; }
            set { _Alt_Anab = value; }
        }

        string _Tipo_Faro_UnicoSx;

        /// <summary>
        /// Gets or sets the value of variable Tipo_Faro_UnicoSx.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e52")]
        public string Tipo_Faro_UnicoSx
        {
            get { return _Tipo_Faro_UnicoSx; }
            set { _Tipo_Faro_UnicoSx = value; }
        }

        string _N_Fari;

        /// <summary>
        /// Gets or sets the value of variable N_Fari.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e53")]
        public string N_Fari
        {
            get { return _N_Fari; }
            set { _N_Fari = value; }
        }

        string _Tipo_Faro_DX;

        /// <summary>
        /// Gets or sets the value of variable Tipo_Faro_DX.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e54")]
        public string Tipo_Faro_DX
        {
            get { return _Tipo_Faro_DX; }
            set { _Tipo_Faro_DX = value; }
        }

        string _Az_Servizio;

        /// <summary>
        /// Gets or sets the value of variable Az_Servizio.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e55")]
        public string Az_Servizio
        {
            get { return _Az_Servizio; }
            set { _Az_Servizio = value; }
        }

        string _Schema_Soccorso;

        /// <summary>
        /// Gets or sets the value of variable Schema_Soccorso.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e56")]
        public string Schema_Soccorso
        {
            get { return _Schema_Soccorso; }
            set { _Schema_Soccorso = value; }
        }

        string _Az_Stazio_____namento;

        /// <summary>
        /// Gets or sets the value of variable Az_Stazio_____namento.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e57")]
        public string Az_Stazio_____namento
        {
            get { return _Az_Stazio_____namento; }
            set { _Az_Stazio_____namento = value; }
        }

        string _Imp_Servizio;

        /// <summary>
        /// Gets or sets the value of variable Imp_Servizio.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e58")]
        public string Imp_Servizio
        {
            get { return _Imp_Servizio; }
            set { _Imp_Servizio = value; }
        }

        string _Imp_Soccorso;

        /// <summary>
        /// Gets or sets the value of variable Imp_Soccorso.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e59")]
        public string Imp_Soccorso
        {
            get { return _Imp_Soccorso; }
            set { _Imp_Soccorso = value; }
        }

        string _Imp_Stazio_____namento;

        /// <summary>
        /// Gets or sets the value of variable Imp_Stazio_____namento.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e60")]
        public string Imp_Stazio_____namento
        {
            get { return _Imp_Stazio_____namento; }
            set { _Imp_Stazio_____namento = value; }
        }

        string _N4x4;

        /// <summary>
        /// Gets or sets the value of variable N4x4.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e61")]
        public string N4x4
        {
            get { return _N4x4; }
            set { _N4x4 = value; }
        }

        string _N_Assi;

        /// <summary>
        /// Gets or sets the value of variable N_Assi.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e62")]
        public string N_Assi
        {
            get { return _N_Assi; }
            set { _N_Assi = value; }
        }

        string _Posizione_Asse_Staz;

        /// <summary>
        /// Gets or sets the value of variable Posizione_Asse_Staz.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e63")]
        public string Posizione_Asse_Staz
        {
            get { return _Posizione_Asse_Staz; }
            set { _Posizione_Asse_Staz = value; }
        }

        string _ABS;

        /// <summary>
        /// Gets or sets the value of variable ABS.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e64")]
        public string ABS
        {
            get { return _ABS; }
            set { _ABS = value; }
        }

        string _RuotaSingola;

        /// <summary>
        /// Gets or sets the value of variable RuotaSingola.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e65")]
        public string RuotaSingola
        {
            get { return _RuotaSingola; }
            set { _RuotaSingola = value; }
        }

        string _Inserimento_Misura_Guidato_1;

        /// <summary>
        /// Gets or sets the value of variable Inserimento_Misura_Guidato_1.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e66")]
        public string Inserimento_Misura_Guidato_1
        {
            get { return _Inserimento_Misura_Guidato_1; }
            set { _Inserimento_Misura_Guidato_1 = value; }
        }

        string _Inserimento_Misura_Guidato_2;

        /// <summary>
        /// Gets or sets the value of variable Inserimento_Misura_Guidato_2.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e67")]
        public string Inserimento_Misura_Guidato_2
        {
            get { return _Inserimento_Misura_Guidato_2; }
            set { _Inserimento_Misura_Guidato_2 = value; }
        }

        string _Inserimento_Misura_Guidato_3;

        /// <summary>
        /// Gets or sets the value of variable Inserimento_Misura_Guidato_3.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e68")]
        public string Inserimento_Misura_Guidato_3
        {
            get { return _Inserimento_Misura_Guidato_3; }
            set { _Inserimento_Misura_Guidato_3 = value; }
        }

        string _Inserimento_Misura_Guidato_4;

        /// <summary>
        /// Gets or sets the value of variable Inserimento_Misura_Guidato_4.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e69")]
        public string Inserimento_Misura_Guidato_4
        {
            get { return _Inserimento_Misura_Guidato_4; }
            set { _Inserimento_Misura_Guidato_4 = value; }
        }

        string _Inserimento_Misura_Guidato_5;

        /// <summary>
        /// Gets or sets the value of variable Inserimento_Misura_Guidato_5.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e70")]
        public string Inserimento_Misura_Guidato_5
        {
            get { return _Inserimento_Misura_Guidato_5; }
            set { _Inserimento_Misura_Guidato_5 = value; }
        }

        string _Inserimento_Misura_Guidato_Diretto;

        /// <summary>
        /// Gets or sets the value of variable Inserimento_Misura_Guidato_Diretto.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e71")]
        public string Inserimento_Misura_Guidato_Diretto
        {
            get { return _Inserimento_Misura_Guidato_Diretto; }
            set { _Inserimento_Misura_Guidato_Diretto = value; }
        }

        string _Tipo;

        /// <summary>
        /// Gets or sets the value of variable Tipo.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e72")]
        public string Tipo
        {
            get { return _Tipo; }
            set { _Tipo = value; }
        }

        string _Cognome;

        /// <summary>
        /// Gets or sets the value of variable Cognome.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e73")]
        public string Cognome
        {
            get { return _Cognome; }
            set { _Cognome = value; }
        }

        string _Nome;

        /// <summary>
        /// Gets or sets the value of variable Nome.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e74")]
        public string Nome
        {
            get { return _Nome; }
            set { _Nome = value; }
        }

        string _Comune;

        /// <summary>
        /// Gets or sets the value of variable Comune.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e75")]
        public string Comune
        {
            get { return _Comune; }
            set { _Comune = value; }
        }

        string _Localita;

        /// <summary>
        /// Gets or sets the value of variable Localita.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e76")]
        public string Localita
        {
            get { return _Localita; }
            set { _Localita = value; }
        }

        string _Provincia;

        /// <summary>
        /// Gets or sets the value of variable Provincia.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e77")]
        public string Provincia
        {
            get { return _Provincia; }
            set { _Provincia = value; }
        }

        string _Tipo_Strada;

        /// <summary>
        /// Gets or sets the value of variable Tipo_Strada.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e78")]
        public string Tipo_Strada
        {
            get { return _Tipo_Strada; }
            set { _Tipo_Strada = value; }
        }

        string _Nome_Strada;

        /// <summary>
        /// Gets or sets the value of variable Nome_Strada.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e79")]
        public string Nome_Strada
        {
            get { return _Nome_Strada; }
            set { _Nome_Strada = value; }
        }

        string _Num_;

        /// <summary>
        /// Gets or sets the value of variable Num_.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e80")]
        public string Num_
        {
            get { return _Num_; }
            set { _Num_ = value; }
        }

        string _Cap;

        /// <summary>
        /// Gets or sets the value of variable Cap.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e81")]
        public string Cap
        {
            get { return _Cap; }
            set { _Cap = value; }
        }

        string _Comune_Nascita;

        /// <summary>
        /// Gets or sets the value of variable Comune_Nascita.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e82")]
        public string Comune_Nascita
        {
            get { return _Comune_Nascita; }
            set { _Comune_Nascita = value; }
        }

        string _Nato_Estero;

        /// <summary>
        /// Gets or sets the value of variable Nato_Estero.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e83")]
        public string Nato_Estero
        {
            get { return _Nato_Estero; }
            set { _Nato_Estero = value; }
        }

        string _Data_Nascita;

        /// <summary>
        /// Gets or sets the value of variable Data_Nascita.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e84")]
        public string Data_Nascita
        {
            get { return _Data_Nascita; }
            set { _Data_Nascita = value; }
        }

        string _Invio_Richiamo;

        /// <summary>
        /// Gets or sets the value of variable Invio_Richiamo.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e86")]
        public string Invio_Richiamo
        {
            get { return _Invio_Richiamo; }
            set { _Invio_Richiamo = value; }
        }

        string _Preferenza;

        /// <summary>
        /// Gets or sets the value of variable Preferenza.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e87")]
        public string Preferenza
        {
            get { return _Preferenza; }
            set { _Preferenza = value; }
        }

        string _Fisso;

        /// <summary>
        /// Gets or sets the value of variable Fisso.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e88")]
        public string Fisso
        {
            get { return _Fisso; }
            set { _Fisso = value; }
        }

        string _Cellulare;

        /// <summary>
        /// Gets or sets the value of variable Cellulare.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e89")]
        public string Cellulare
        {
            get { return _Cellulare; }
            set { _Cellulare = value; }
        }

        string _Fax;

        /// <summary>
        /// Gets or sets the value of variable Fax.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e90")]
        public string Fax
        {
            get { return _Fax; }
            set { _Fax = value; }
        }

        string _Mail;

        /// <summary>
        /// Gets or sets the value of variable Mail.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e91")]
        public string Mail
        {
            get { return _Mail; }
            set { _Mail = value; }
        }

        string _Categoria_Anagrafica;

        /// <summary>
        /// Gets or sets the value of variable Categoria_Anagrafica.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e92")]
        public string Categoria_Anagrafica
        {
            get { return _Categoria_Anagrafica; }
            set { _Categoria_Anagrafica = value; }
        }

        string _P_Iva;

        /// <summary>
        /// Gets or sets the value of variable P_Iva.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e93")]
        public string P_Iva
        {
            get { return _P_Iva; }
            set { _P_Iva = value; }
        }

        string _Cod_Fiscale;

        /// <summary>
        /// Gets or sets the value of variable Cod_Fiscale.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e94")]
        public string Cod_Fiscale
        {
            get { return _Cod_Fiscale; }
            set { _Cod_Fiscale = value; }
        }

        string _Doc_Identita_Patente;

        /// <summary>
        /// Gets or sets the value of variable Doc_Identita_Patente.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e95")]
        public string Doc_Identita_Patente
        {
            get { return _Doc_Identita_Patente; }
            set { _Doc_Identita_Patente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Sesso.
        /// </summary>
        [TestVariable("1321fcd1-135a-4a97-b612-fe1d45e94e85")]
        public string Sesso
        {
            get { return repo.Sesso; }
            set { repo.Sesso = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            // Inserimento nuova Ispezione - Dati Identificativi
            Report.Log(ReportLevel.Info, "Section", "Inserimento nuova Ispezione - Dati Identificativi", new RecordItemIndex(0));
            
            // ############################################### DATI TECNICI ###############################################
            Report.Log(ReportLevel.Info, "Section", "############################################### DATI TECNICI ###############################################", new RecordItemIndex(1));
            
            // Inserimento CATEGORIA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento CATEGORIA\r\nMouse Left Click item 'ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CatVeicolo' at Center.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CatVeicoloInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CatVeicolo.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CatVeicolo' at Center.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CatVeicoloInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CatVeicolo.DoubleClick();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Categoria' with focus on 'ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CatVeicolo'.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CatVeicoloInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CatVeicolo.PressKeys(Categoria);
            
            // Inserimento CIC
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento CIC\r\nMouse Left Click item 'ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CIC' at Center.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CICInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CIC.Click();
            
            // Inserimento CIC
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento CIC\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CIC' at Center.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CICInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CIC.DoubleClick();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CIC'.", new RecordItemIndex(7));
            Keyboard.Press(CIC);
            
            // Inserimento TARGA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento TARGA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_TARGA' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_TARGAInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_TARGA.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Targa'.", new RecordItemIndex(9));
            Keyboard.Press(Targa);
            
            // Inserimento TELAIO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento TELAIO\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_Telaio' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_TelaioInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_Telaio.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Telaio'.", new RecordItemIndex(11));
            Keyboard.Press(Telaio);
            
            // Inserimento KM
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento KM\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_Km' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_KmInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_Km.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$KM'.", new RecordItemIndex(13));
            Keyboard.Press(KM);
            
            // Inserimento OMOLOGAZIONE
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento OMOLOGAZIONE\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_Omologazione' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_OmologazioneInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_Omologazione.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Omologazione'.", new RecordItemIndex(15));
            Keyboard.Press(Omologazione);
            
            // Inserimento MARCA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento MARCA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_Marca' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_MarcaInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_Marca.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Marca'.", new RecordItemIndex(17));
            Keyboard.Press(Marca);
            
            // Inserimento MODELLO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento MODELLO\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_Modello' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_ModelloInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_Modello.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Modello'.", new RecordItemIndex(19));
            Keyboard.Press(Modello);
            
            // Inserimento NUMERO POSTI
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento NUMERO POSTI\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_NPosti' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_NPostiInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_NPosti.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$N_Posti'.", new RecordItemIndex(21));
            Keyboard.Press(N_Posti);
            
            // Inserimento DATA IMMATRICOLAZIONE
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento DATA IMMATRICOLAZIONE\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_DataImmatricolazione' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_DataImmatricolazioneInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_DataImmatricolazione.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Data_Imm'.", new RecordItemIndex(23));
            Keyboard.Press(Data_Imm);
            
            // Inserimento DATA RILASCIO CARTA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento DATA RILASCIO CARTA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_DataRilascioCarta' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_DataRilascioCartaInfo, new RecordItemIndex(24));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_DataRilascioCarta.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$RilascioCarta'.", new RecordItemIndex(25));
            Keyboard.Press(RilascioCarta);
            
            // Inserimento COMMITTENTE
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento COMMITTENTE\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_Committente' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_CommittenteInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiIdentificativi_Committente.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Committente'.", new RecordItemIndex(27));
            Keyboard.Press(Committente);
            
            // Inserimento nuova ispezione - Dati tecnici del veicolo
            Report.Log(ReportLevel.Info, "Section", "Inserimento nuova ispezione - Dati tecnici del veicolo", new RecordItemIndex(28));
            
            // Inserimento 1*ALIMENTAZIONE
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento 1*ALIMENTAZIONE\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_Alimentazione1' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_Alimentazione1Info, new RecordItemIndex(29));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_Alimentazione1.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$N1Alimentazione'.", new RecordItemIndex(30));
            Keyboard.Press(N1Alimentazione);
            
            // Inserimento 2*ALIMENTAZIONE
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento 2*ALIMENTAZIONE\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_Alimentazione2' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_Alimentazione2Info, new RecordItemIndex(31));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_Alimentazione2.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$N2Alimentazione'.", new RecordItemIndex(32));
            Keyboard.Press(N2Alimentazione);
            
            // Inserimento DI FABBRICA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento DI FABBRICA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_DiFabbrica' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_DiFabbricaInfo, new RecordItemIndex(33));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_DiFabbrica.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$DiFabbrica'.", new RecordItemIndex(34));
            Keyboard.Press(DiFabbrica);
            
            // Inserimento TIPO MOTORE
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento TIPO MOTORE\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_TipoMotore' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_TipoMotoreInfo, new RecordItemIndex(35));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_TipoMotore.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TipoMotore'.", new RecordItemIndex(36));
            Keyboard.Press(TipoMotore);
            
            // Inserimento TEMPI MOTORE
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento TEMPI MOTORE\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_TempiMotore' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_TempiMotoreInfo, new RecordItemIndex(37));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_TempiMotore.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Tempi'.", new RecordItemIndex(38));
            Keyboard.Press(Tempi);
            
            // Inserimento NUMERO CILINDRI
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento NUMERO CILINDRI\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_NumCilindri' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_NumCilindriInfo, new RecordItemIndex(39));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_NumCilindri.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$N_Cilindri'.", new RecordItemIndex(40));
            Keyboard.Press(N_Cilindri);
            
            // Inserimento CILINDRATA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento CILINDRATA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_Cilindrata' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_CilindrataInfo, new RecordItemIndex(41));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_Cilindrata.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Cilindrata'.", new RecordItemIndex(42));
            Keyboard.Press(Cilindrata);
            
            // Inserimento TIPO CAMBIO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento TIPO CAMBIO\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_TipoCambio' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_TipoCambioInfo, new RecordItemIndex(43));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_TipoCambio.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TipoCambio'.", new RecordItemIndex(44));
            Keyboard.Press(TipoCambio);
            
            // Inserimento POTENZA CAVALLI
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento POTENZA CAVALLI\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_PtCavalli' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_PtCavalliInfo, new RecordItemIndex(45));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_PtCavalli.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Pt_CV'.", new RecordItemIndex(46));
            Keyboard.Press(Pt_CV);
            
            // Inserimento POTENZA KILOWATT
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento POTENZA KILOWATT\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_PtKilowatt' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_PtKilowattInfo, new RecordItemIndex(47));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_PtKilowatt.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Pt_KW'.", new RecordItemIndex(48));
            Keyboard.Press(Pt_KW);
            
            // Inserimento SCADENZA IMPIANTO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento SCADENZA IMPIANTO\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_DataScadenzaImpianto' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_DataScadenzaImpiantoInfo, new RecordItemIndex(49));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiTecniciVeicolo_DataScadenzaImpianto.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Scad_Imp_GPLMet'.", new RecordItemIndex(50));
            Keyboard.Press(Scad_Imp_GPLMet);
            
            // Inserimento nuova ispezione - Masse
            Report.Log(ReportLevel.Info, "Section", "Inserimento nuova ispezione - Masse", new RecordItemIndex(51));
            
            // Inserimento TARA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento TARA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Masse_Tara' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Masse_TaraInfo, new RecordItemIndex(52));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Masse_Tara.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Tara'.", new RecordItemIndex(53));
            Keyboard.Press(Tara);
            
            // Inserimento MASSA MASSIMA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento MASSA MASSIMA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Masse_MassaMax' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Masse_MassaMaxInfo, new RecordItemIndex(54));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Masse_MassaMax.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$MassaMassima'.", new RecordItemIndex(55));
            Keyboard.Press(MassaMassima);
            
            // Settaggio TRAINO
            Report.Log(ReportLevel.Info, "Mouse", "Settaggio TRAINO\r\nMouse Left Click item 'ApplicationUnderTest.RootGrid.Ispezione_Masse_Traino' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Masse_TrainoInfo, new RecordItemIndex(56));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Masse_Traino.Click("64;11");
            
            // Inserimento MASSA RIM.
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento MASSA RIM.\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Masse_MassaRim' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Masse_MassaRimInfo, new RecordItemIndex(57));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Masse_MassaRim.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$MassaRim'.", new RecordItemIndex(58));
            Keyboard.Press(MassaRim);
            
            // Inserimento nuova ispezione - Emissioni
            Report.Log(ReportLevel.Info, "Section", "Inserimento nuova ispezione - Emissioni", new RecordItemIndex(59));
            
            // Inserimento MAX DECIBEL
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento MAX DECIBEL\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Emissioni_MaxDB' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_MaxDBInfo, new RecordItemIndex(60));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_MaxDB.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$MaxDB'.", new RecordItemIndex(61));
            Keyboard.Press(MaxDB);
            
            // Inserimento GIRI MOTORE DECIBEL
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento GIRI MOTORE DECIBEL\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Emissioni_GiriMotoreDB' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_GiriMotoreDBInfo, new RecordItemIndex(62));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_GiriMotoreDB.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GiriMotoreDB'.", new RecordItemIndex(63));
            Keyboard.Press(GiriMotoreDB);
            
            // Inserimento GIRI MAX
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento GIRI MAX\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Emissioni_GiriMax' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_GiriMaxInfo, new RecordItemIndex(64));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_GiriMax.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GiriMax'.", new RecordItemIndex(65));
            Keyboard.Press(GiriMax);
            
            // Inserimento LIMITE GIRI
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento LIMITE GIRI\r\nMouse Left Click item 'ApplicationUnderTest.RootGrid.Ispezione_Emissioni_LimiteGiri' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_LimiteGiriInfo, new RecordItemIndex(66));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_LimiteGiri.Click("64;11");
            
            // Inserimento DIRETTIVE EMISSIONI
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento DIRETTIVE EMISSIONI\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Emissioni_DirettivaEmisisoni' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_DirettivaEmisisoniInfo, new RecordItemIndex(67));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_DirettivaEmisisoni.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Dir_Emiss_Scarico'.", new RecordItemIndex(68));
            Keyboard.Press(Dir_Emiss_Scarico);
            
            // Inserimento DIRETTIVA ACUSTICA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento DIRETTIVA ACUSTICA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Emissioni_DirettivaAcustica' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_DirettivaAcusticaInfo, new RecordItemIndex(69));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_DirettivaAcustica.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Direttiva_Acustica'.", new RecordItemIndex(70));
            Keyboard.Press(Direttiva_Acustica);
            
            // Inserimento DIRETTIVA AVV. ACUSTICA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento DIRETTIVA AVV. ACUSTICA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Emissioni_DirettivaAvvAcustico' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_DirettivaAvvAcusticoInfo, new RecordItemIndex(71));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_DirettivaAvvAcustico.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Dir_Avvio_Acustico'.", new RecordItemIndex(72));
            Keyboard.Press(Dir_Avvio_Acustico);
            
            // Inserimento LIMITI LAMBDA MIN
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento LIMITI LAMBDA MIN\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Emissioni_LambdaLimitMin' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_LambdaLimitMinInfo, new RecordItemIndex(73));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_LambdaLimitMin.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Limiti_Lambda_Min'.", new RecordItemIndex(74));
            Keyboard.Press(Limiti_Lambda_Min);
            
            // Inserimento LIMITI LAMBDA MAX
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento LIMITI LAMBDA MAX\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Emissioni_LambdaLimitMax' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_LambdaLimitMaxInfo, new RecordItemIndex(75));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_LambdaLimitMax.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Limiti_Lambda_Max'.", new RecordItemIndex(76));
            Keyboard.Press(Limiti_Lambda_Max);
            
            // Inserimento LIMITE K
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento LIMITE K\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Emissioni_LimiteK' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_LimiteKInfo, new RecordItemIndex(77));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_LimiteK.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Limite_K'.", new RecordItemIndex(78));
            Keyboard.Press(Limite_K);
            
            // Inserimento N° SCARICHI
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento N° SCARICHI\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Emissioni_NScarichi' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_NScarichiInfo, new RecordItemIndex(79));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_NScarichi.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$N_Scarichiq'.", new RecordItemIndex(80));
            Keyboard.Press(N_Scarichiq);
            
            // Inserimento >30 CM
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento >30 CM\r\nMouse Left Click item 'ApplicationUnderTest.RootGrid.Ispezione_Emissioni_30Cm' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_30CmInfo, new RecordItemIndex(81));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Emissioni_30Cm.Click("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$N30cm'.", new RecordItemIndex(82));
            Keyboard.Press(N30cm);
            
            // Inserimento nuova ispezione - Fari
            Report.Log(ReportLevel.Info, "Section", "Inserimento nuova ispezione - Fari", new RecordItemIndex(83));
            
            // Inserimento ALT. ANABBAGLIANTI
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento ALT. ANABBAGLIANTI\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Fari_AltAnab' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Fari_AltAnabInfo, new RecordItemIndex(84));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Fari_AltAnab.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Alt_Anab'.", new RecordItemIndex(85));
            Keyboard.Press(Alt_Anab);
            
            // Inserimento TIPO FARO UNICO/SX
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento TIPO FARO UNICO/SX\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Fari_TipoFaroUnicoSX' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Fari_TipoFaroUnicoSXInfo, new RecordItemIndex(86));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Fari_TipoFaroUnicoSX.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Tipo_Faro_UnicoSx'.", new RecordItemIndex(87));
            Keyboard.Press(Tipo_Faro_UnicoSx);
            
            // Inserimento N°FARI
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento N°FARI\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Fari_NFari' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Fari_NFariInfo, new RecordItemIndex(88));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Fari_NFari.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$N_Fari'.", new RecordItemIndex(89));
            Keyboard.Press(N_Fari);
            
            // Inserimento TIPO FARO DX
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento TIPO FARO DX\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Fari_TipoFaroDX' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Fari_TipoFaroDXInfo, new RecordItemIndex(90));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Fari_TipoFaroDX.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Tipo_Faro_DX'.", new RecordItemIndex(91));
            Keyboard.Press(Tipo_Faro_DX);
            
            // Inserimento nuova ispezione - Impianto Frenante
            Report.Log(ReportLevel.Info, "Section", "Inserimento nuova ispezione - Impianto Frenante", new RecordItemIndex(92));
            
            // Inserimento AZ SERVIZIO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento AZ SERVIZIO\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_AzServizio' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_AzServizioInfo, new RecordItemIndex(93));
            repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_AzServizio.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Az_Servizio'.", new RecordItemIndex(94));
            Keyboard.Press(Az_Servizio);
            
            // Inserimento SCHEMA SOCCORSO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento SCHEMA SOCCORSO\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_SchemaSoccorso' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_SchemaSoccorsoInfo, new RecordItemIndex(95));
            repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_SchemaSoccorso.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Schema_Soccorso'.", new RecordItemIndex(96));
            Keyboard.Press(Schema_Soccorso);
            
            // Inserimento AZ. STAZIONAMENTO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento AZ. STAZIONAMENTO\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_AzStazionamento' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_AzStazionamentoInfo, new RecordItemIndex(97));
            repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_AzStazionamento.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Az_Stazio_____namento'.", new RecordItemIndex(98));
            Keyboard.Press(Az_Stazio_____namento);
            
            // Inserimento IMPIANTO SERVIZIO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento IMPIANTO SERVIZIO\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_ImpServizio' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_ImpServizioInfo, new RecordItemIndex(99));
            repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_ImpServizio.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Imp_Servizio'.", new RecordItemIndex(100));
            Keyboard.Press(Imp_Servizio);
            
            // Inserimento IMPIANTO SOCCORSO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento IMPIANTO SOCCORSO\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_ImpSoccorso' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_ImpSoccorsoInfo, new RecordItemIndex(101));
            repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_ImpSoccorso.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Imp_Soccorso'.", new RecordItemIndex(102));
            Keyboard.Press(Imp_Soccorso);
            
            // Inserimento IMPIANTO STAZIONAMENTO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento IMPIANTO STAZIONAMENTO\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_ImpStazionamento' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_ImpStazionamentoInfo, new RecordItemIndex(103));
            repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_ImpStazionamento.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Imp_Stazio_____namento'.", new RecordItemIndex(104));
            Keyboard.Press(Imp_Stazio_____namento);
            
            // Inserimento 4X4
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento 4X4\r\nMouse Left Click item 'ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_4x4' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_4x4Info, new RecordItemIndex(105));
            repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_4x4.Click("64;11");
            
            // Inserimento N° ASSI
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento N° ASSI\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_NAssi' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_NAssiInfo, new RecordItemIndex(106));
            repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_NAssi.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$N_Assi'.", new RecordItemIndex(107));
            Keyboard.Press(N_Assi);
            
            // Inserimento POSIZIONE ASSE STAZ.
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento POSIZIONE ASSE STAZ.\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_PosizioneAsseStaz' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_PosizioneAsseStazInfo, new RecordItemIndex(108));
            repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_PosizioneAsseStaz.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Posizione_Asse_Staz'.", new RecordItemIndex(109));
            Keyboard.Press(Posizione_Asse_Staz);
            
            // Inserimento ABS
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento ABS\r\nMouse Left Click item 'ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_ABS' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_ABSInfo, new RecordItemIndex(110));
            repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_ABS.Click("64;11");
            
            // Inserimento RUOTA SINGOLA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento RUOTA SINGOLA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_RuotaSingola' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_RuotaSingolaInfo, new RecordItemIndex(111));
            repo.ApplicationUnderTest.RootGrid.Ispezione_ImpiantoFrenante_RuotaSingola.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$RuotaSingola'.", new RecordItemIndex(112));
            Keyboard.Press(RuotaSingola);
            
            // Inserimento nuova ispezione - Pneumatici
            Report.Log(ReportLevel.Info, "Section", "Inserimento nuova ispezione - Pneumatici", new RecordItemIndex(113));
            
            // Inserimento PNEUMATICI DIRETTO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento PNEUMATICI DIRETTO\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Pneumatici_InserimentoDiretto' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Pneumatici_InserimentoDirettoInfo, new RecordItemIndex(114));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Pneumatici_InserimentoDiretto.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Inserimento_Misura_Guidato_Diretto'.", new RecordItemIndex(115));
            Keyboard.Press(Inserimento_Misura_Guidato_Diretto);
            
            // ############################################### PROPRIETARIO / CONDUCENTE ###############################################
            Report.Log(ReportLevel.Info, "Section", "############################################### PROPRIETARIO / CONDUCENTE ###############################################", new RecordItemIndex(116));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DatiRevisione.BtnProprietario' at Center.", repo.ApplicationUnderTest.DatiRevisione.BtnProprietarioInfo, new RecordItemIndex(117));
            repo.ApplicationUnderTest.DatiRevisione.BtnProprietario.Click();
            
            // Inserimento nuova ispezione - Dati anagrafici Proprietario
            Report.Log(ReportLevel.Info, "Section", "Inserimento nuova ispezione - Dati anagrafici Proprietario", new RecordItemIndex(118));
            
            // Inserimento TIPO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento TIPO\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_TipoProprietario' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_TipoProprietarioInfo, new RecordItemIndex(119));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_TipoProprietario.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Tipo'.", new RecordItemIndex(120));
            Keyboard.Press(Tipo);
            
            // Inserimento COGNOME
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento COGNOME\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_Cognome' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_CognomeInfo, new RecordItemIndex(121));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_Cognome.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Cognome'.", new RecordItemIndex(122));
            Keyboard.Press(Cognome);
            
            // Inserimento NOME
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento NOME\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_Nome' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_NomeInfo, new RecordItemIndex(123));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_Nome.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Nome'.", new RecordItemIndex(124));
            Keyboard.Press(Nome);
            
            // Inserimento COMUNE
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento COMUNE\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_ComuneResidenza' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_ComuneResidenzaInfo, new RecordItemIndex(125));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_ComuneResidenza.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Comune'.", new RecordItemIndex(126));
            Keyboard.Press(Comune);
            
            // Inserimento LOCALITA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento LOCALITA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_Localita' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_LocalitaInfo, new RecordItemIndex(127));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_Localita.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Localita'.", new RecordItemIndex(128));
            Keyboard.Press(Localita);
            
            // Inserimento PROVINCIA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento PROVINCIA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_Provincia' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_ProvinciaInfo, new RecordItemIndex(129));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_Provincia.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Provincia'.", new RecordItemIndex(130));
            Keyboard.Press(Provincia);
            
            // Inserimento TIPO STARDA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento TIPO STARDA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_TipiStrada' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_TipiStradaInfo, new RecordItemIndex(131));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_TipiStrada.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Tipo_Strada'.", new RecordItemIndex(132));
            Keyboard.Press(Tipo_Strada);
            
            // Inserimento NOME STRADA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento NOME STRADA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_NomiStrada' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_NomiStradaInfo, new RecordItemIndex(133));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_NomiStrada.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Nome_Strada'.", new RecordItemIndex(134));
            Keyboard.Press(Nome_Strada);
            
            // Inserimento CIVICO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento CIVICO\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_NumCivico' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_NumCivicoInfo, new RecordItemIndex(135));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_NumCivico.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Num_'.", new RecordItemIndex(136));
            Keyboard.Press(Num_);
            
            // Inserimento CAP
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento CAP\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_CAP' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_CAPInfo, new RecordItemIndex(137));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_CAP.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Cap'.", new RecordItemIndex(138));
            Keyboard.Press(Cap);
            
            // Inserimento COMUNE DI NASCITA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento COMUNE DI NASCITA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_ComuneNascita' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_ComuneNascitaInfo, new RecordItemIndex(139));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_ComuneNascita.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Comune_Nascita'.", new RecordItemIndex(140));
            Keyboard.Press(Comune_Nascita);
            
            // Inserimento NATO ALL'ESTERO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento NATO ALL'ESTERO\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_NatoAllEstero' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_NatoAllEsteroInfo, new RecordItemIndex(141));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_NatoAllEstero.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Nato_Estero'.", new RecordItemIndex(142));
            Keyboard.Press(Nato_Estero);
            
            // Inserimento DAT DI NASCITA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento DAT DI NASCITA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_DataNascita' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_DataNascitaInfo, new RecordItemIndex(143));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_DataNascita.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Data_Nascita'.", new RecordItemIndex(144));
            Keyboard.Press(Data_Nascita);
            
            SetSesso();
            
            // Inserimento SESSO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento SESSO\r\nMouse Left Click item 'ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_Sesso_MASCHIO' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_Sesso_MASCHIOInfo, new RecordItemIndex(146));
            repo.ApplicationUnderTest.RootGrid.Ispezione_DatiAnagraficiProprietario_Sesso_MASCHIO.Click("64;11");
            
            // Inserimento nuova ispezione - Contatti
            Report.Log(ReportLevel.Info, "Section", "Inserimento nuova ispezione - Contatti", new RecordItemIndex(147));
            
            // Settaggio INVIO RICHAIMO
            Report.Log(ReportLevel.Info, "Mouse", "Settaggio INVIO RICHAIMO\r\nMouse Left Click item 'ApplicationUnderTest.RootGrid.Ispezione_Contatti_InvioRichiamo' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Contatti_InvioRichiamoInfo, new RecordItemIndex(148));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Contatti_InvioRichiamo.Click("64;11");
            
            // Inserimento PREFERENZA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento PREFERENZA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Contatti_Preferenza' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Contatti_PreferenzaInfo, new RecordItemIndex(149));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Contatti_Preferenza.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Preferenza'.", new RecordItemIndex(150));
            Keyboard.Press(Preferenza);
            
            // Inserimento FISSO
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento FISSO\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Contatti_Fisso' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Contatti_FissoInfo, new RecordItemIndex(151));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Contatti_Fisso.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Fisso'.", new RecordItemIndex(152));
            Keyboard.Press(Fisso);
            
            // Inserimento CELLULARE
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento CELLULARE\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Contatti_Cellulare' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Contatti_CellulareInfo, new RecordItemIndex(153));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Contatti_Cellulare.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Cellulare'.", new RecordItemIndex(154));
            Keyboard.Press(Cellulare);
            
            // Inserimento FAX
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento FAX\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Contatti_Fax' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Contatti_FaxInfo, new RecordItemIndex(155));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Contatti_Fax.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Fax'.", new RecordItemIndex(156));
            Keyboard.Press(Fax);
            
            // Inserimento MAIL
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento MAIL\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Contatti_Mail' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Contatti_MailInfo, new RecordItemIndex(157));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Contatti_Mail.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Mail'.", new RecordItemIndex(158));
            Keyboard.Press(Mail);
            
            // Inserimento CATEGORIA ANAGRAFICA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento CATEGORIA ANAGRAFICA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_Contatti_CategoriaAnagrafica' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_Contatti_CategoriaAnagraficaInfo, new RecordItemIndex(159));
            repo.ApplicationUnderTest.RootGrid.Ispezione_Contatti_CategoriaAnagrafica.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Categoria_Anagrafica'.", new RecordItemIndex(160));
            Keyboard.Press(Categoria_Anagrafica);
            
            // Inserimento nuova ispezione - Altri dati
            Report.Log(ReportLevel.Info, "Section", "Inserimento nuova ispezione - Altri dati", new RecordItemIndex(161));
            
            // Inserimento PARTITA IVA
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento PARTITA IVA\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_AltriDati_PIVA' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_AltriDati_PIVAInfo, new RecordItemIndex(162));
            repo.ApplicationUnderTest.RootGrid.Ispezione_AltriDati_PIVA.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$P_Iva'.", new RecordItemIndex(163));
            Keyboard.Press(P_Iva);
            
            // Inserimento CODICE FISCALE
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento CODICE FISCALE\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_AltriDati_CodiceFiscale' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_AltriDati_CodiceFiscaleInfo, new RecordItemIndex(164));
            repo.ApplicationUnderTest.RootGrid.Ispezione_AltriDati_CodiceFiscale.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Cod_Fiscale'.", new RecordItemIndex(165));
            Keyboard.Press(Cod_Fiscale);
            
            // Inserimento DOCUMENTO DI IDENTITA/PATENTE
            Report.Log(ReportLevel.Info, "Mouse", "Inserimento DOCUMENTO DI IDENTITA/PATENTE\r\nMouse Left DoubleClick item 'ApplicationUnderTest.RootGrid.Ispezione_AltriDati_PIVA' at 64;11.", repo.ApplicationUnderTest.RootGrid.Ispezione_AltriDati_PIVAInfo, new RecordItemIndex(166));
            repo.ApplicationUnderTest.RootGrid.Ispezione_AltriDati_PIVA.DoubleClick("64;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Doc_Identita_Patente'.", new RecordItemIndex(167));
            Keyboard.Press(Doc_Identita_Patente);
            
            // ############################################### ACCETTAZIONE \ INVIO ALLA LINEA ###############################################
            Report.Log(ReportLevel.Info, "Section", "############################################### ACCETTAZIONE \\ INVIO ALLA LINEA ###############################################", new RecordItemIndex(168));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DatiRevisione.BtnAccettazione' at Center.", repo.ApplicationUnderTest.DatiRevisione.BtnAccettazioneInfo, new RecordItemIndex(169));
            repo.ApplicationUnderTest.DatiRevisione.BtnAccettazione.Click();
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DatiRevisione.Ispezione_SalvaAccettazione' at Center.", repo.ApplicationUnderTest.DatiRevisione.Ispezione_SalvaAccettazioneInfo, new RecordItemIndex(170));
            //repo.ApplicationUnderTest.DatiRevisione.Ispezione_SalvaAccettazione.Click();
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 5m to exist. Associated repository item: 'ApplicationUnderTest.DomandaRevisione.Ispezione_StampaDomanda_Form'", repo.ApplicationUnderTest.DomandaRevisione.Ispezione_StampaDomanda_FormInfo, new ActionTimeout(300000), new RecordItemIndex(171));
            //repo.ApplicationUnderTest.DomandaRevisione.Ispezione_StampaDomanda_FormInfo.WaitForExists(300000);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DomandaRevisione.Ispezione_ApriDomandaRevisione' at Center.", repo.ApplicationUnderTest.DomandaRevisione.Ispezione_ApriDomandaRevisioneInfo, new RecordItemIndex(172));
            //repo.ApplicationUnderTest.DomandaRevisione.Ispezione_ApriDomandaRevisione.Click();
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RootGrid.Ispezione_NuovoInserimento' at Center.", repo.ApplicationUnderTest.RootGrid.Ispezione_NuovoInserimentoInfo, new RecordItemIndex(173));
            //repo.ApplicationUnderTest.RootGrid.Ispezione_NuovoInserimento.Click();
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 2m to exist. Associated repository item: 'ApplicationUnderTest.RootGrid.msgbx_AnnullamentoModifiche'", repo.ApplicationUnderTest.RootGrid.msgbx_AnnullamentoModificheInfo, new ActionTimeout(120000), new RecordItemIndex(174));
            //repo.ApplicationUnderTest.RootGrid.msgbx_AnnullamentoModificheInfo.WaitForExists(120000);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RootGrid.msgbx_AnnullamentoModifche_yes' at Center.", repo.ApplicationUnderTest.RootGrid.msgbx_AnnullamentoModifche_yesInfo, new RecordItemIndex(175));
            //repo.ApplicationUnderTest.RootGrid.msgbx_AnnullamentoModifche_yes.Click();
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 20s.", new RecordItemIndex(176));
            Delay.Duration(20000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
