///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AvvioProgramma
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AvvioProgrammaRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("321afda6-80ed-48f7-90b4-f02c00670818")]
    public partial class AvvioProgrammaRepository : RepoGenBaseFolder
    {
        static AvvioProgrammaRepository instance = new AvvioProgrammaRepository();

        /// <summary>
        /// Gets the singleton class instance representing the AvvioProgrammaRepository element repository.
        /// </summary>
        [RepositoryFolder("321afda6-80ed-48f7-90b4-f02c00670818")]
        public static AvvioProgrammaRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AvvioProgrammaRepository() 
            : base("AvvioProgrammaRepository", "/", null, 0, false, "321afda6-80ed-48f7-90b4-f02c00670818", ".\\RepositoryImages\\AvvioProgrammaRepository321afda6.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("321afda6-80ed-48f7-90b4-f02c00670818")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AvvioProgrammaRepositoryFolders
    {
    }
#pragma warning restore 0436
}
