///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace G4_TEST_POST_RILASCIO._xx__ChiusuraProgramma
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ChiusuraG4 recording.
    /// </summary>
    [TestModule("68efe10a-f795-447b-b273-f9f2421beb14", ModuleType.Recording, 1)]
    public partial class ChiusuraG4 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::G4_TEST_POST_RILASCIO.G4_TEST_POST_RILASCIORepository repository.
        /// </summary>
        public static global::G4_TEST_POST_RILASCIO.G4_TEST_POST_RILASCIORepository repo = global::G4_TEST_POST_RILASCIO.G4_TEST_POST_RILASCIORepository.Instance;

        static ChiusuraG4 instance = new ChiusuraG4();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ChiusuraG4()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ChiusuraG4 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Chiusura del G4
            Report.Log(ReportLevel.Info, "Mouse", "Chiusura del G4\r\nMouse Left Click item 'Chiusura.ChiudiG4' at Center.", repo.Chiusura.ChiudiG4Info, new RecordItemIndex(0));
            repo.Chiusura.ChiudiG4.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to exist. Associated repository item: 'Chiusura.ConfermaChiusura_MsgBx'", repo.Chiusura.ConfermaChiusura_MsgBxInfo, new ActionTimeout(60000), new RecordItemIndex(1));
            repo.Chiusura.ConfermaChiusura_MsgBxInfo.WaitForExists(60000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Chiusura.ConfermaChiusura_MsgBx_Ok' at Center.", repo.Chiusura.ConfermaChiusura_MsgBx_OkInfo, new RecordItemIndex(2));
            repo.Chiusura.ConfermaChiusura_MsgBx_Ok.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
