///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace G4_TEST_POST_RILASCIO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the G4_TEST_POST_RILASCIORepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("dada0f3e-6737-40a8-94dd-3d4f2b715a5e")]
    public partial class G4_TEST_POST_RILASCIORepository : RepoGenBaseFolder
    {
        static G4_TEST_POST_RILASCIORepository instance = new G4_TEST_POST_RILASCIORepository();
        G4_TEST_POST_RILASCIORepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        G4_TEST_POST_RILASCIORepositoryFolders.ChiusuraFolder _chiusura;
        G4_TEST_POST_RILASCIORepositoryFolders.ProxyAppFolder _proxy;
        G4_TEST_POST_RILASCIORepositoryFolders.BackUpAppFolder _backup;
        G4_TEST_POST_RILASCIORepositoryFolders.GesRevNET4AppFolder _gesrevnet4;

        /// <summary>
        /// Gets the singleton class instance representing the G4_TEST_POST_RILASCIORepository element repository.
        /// </summary>
        [RepositoryFolder("dada0f3e-6737-40a8-94dd-3d4f2b715a5e")]
        public static G4_TEST_POST_RILASCIORepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public G4_TEST_POST_RILASCIORepository() 
            : base("G4_TEST_POST_RILASCIORepository", "/", null, 0, false, "dada0f3e-6737-40a8-94dd-3d4f2b715a5e", ".\\RepositoryImages\\G4_TEST_POST_RILASCIORepositorydada0f3e.rximgres")
        {
            _applicationundertest = new G4_TEST_POST_RILASCIORepositoryFolders.ApplicationUnderTestAppFolder(this);
            _chiusura = new G4_TEST_POST_RILASCIORepositoryFolders.ChiusuraFolder(this);
            _proxy = new G4_TEST_POST_RILASCIORepositoryFolders.ProxyAppFolder(this);
            _backup = new G4_TEST_POST_RILASCIORepositoryFolders.BackUpAppFolder(this);
            _gesrevnet4 = new G4_TEST_POST_RILASCIORepositoryFolders.GesRevNET4AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("dada0f3e-6737-40a8-94dd-3d4f2b715a5e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("f08d598a-b0d6-49b3-ab4d-72f1eb766924")]
        public virtual G4_TEST_POST_RILASCIORepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Chiusura folder.
        /// </summary>
        [RepositoryFolder("157c1c07-a34e-4690-8b91-97412284a983")]
        public virtual G4_TEST_POST_RILASCIORepositoryFolders.ChiusuraFolder Chiusura
        {
            get { return _chiusura; }
        }

        /// <summary>
        /// The Proxy folder.
        /// </summary>
        [RepositoryFolder("483a9e99-428c-46a9-9492-66d0bb3b1373")]
        public virtual G4_TEST_POST_RILASCIORepositoryFolders.ProxyAppFolder Proxy
        {
            get { return _proxy; }
        }

        /// <summary>
        /// The BackUp folder.
        /// </summary>
        [RepositoryFolder("01fc1f17-086d-49bc-ae9b-850c5873a6c4")]
        public virtual G4_TEST_POST_RILASCIORepositoryFolders.BackUpAppFolder BackUp
        {
            get { return _backup; }
        }

        /// <summary>
        /// The GesRevNET4 folder.
        /// </summary>
        [RepositoryFolder("e30b364a-e253-4aa6-9d8e-adfb3136766b")]
        public virtual G4_TEST_POST_RILASCIORepositoryFolders.GesRevNET4AppFolder GesRevNET4
        {
            get { return _gesrevnet4; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class G4_TEST_POST_RILASCIORepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("f08d598a-b0d6-49b3-ab4d-72f1eb766924")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            G4_TEST_POST_RILASCIORepositoryFolders.LoginFolder _login;
            G4_TEST_POST_RILASCIORepositoryFolders.DomandaRevisioneFolder _domandarevisione;
            G4_TEST_POST_RILASCIORepositoryFolders.DatiRevisioneFolder _datirevisione;
            G4_TEST_POST_RILASCIORepositoryFolders.RootGridFolder _rootgrid;
            RepoItemInfo _tile_ispezioneInfo;
            RepoItemInfo _someelementInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/form[@processname='GesRevNET4']", parentFolder, 30000, null, false, "f08d598a-b0d6-49b3-ab4d-72f1eb766924", "")
            {
                _login = new G4_TEST_POST_RILASCIORepositoryFolders.LoginFolder(this);
                _domandarevisione = new G4_TEST_POST_RILASCIORepositoryFolders.DomandaRevisioneFolder(this);
                _datirevisione = new G4_TEST_POST_RILASCIORepositoryFolders.DatiRevisioneFolder(this);
                _rootgrid = new G4_TEST_POST_RILASCIORepositoryFolders.RootGridFolder(this);
                _tile_ispezioneInfo = new RepoItemInfo(this, "Tile_Ispezione", "container[@automationid='Root_Grid']/?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/container/container[2]/element/container/container[3]/container[2]/element[@automationid='TileInserimento']/container[@automationid='root']/element[@automationid='content']/container[@automationid='UCBaseTileControl']//container[@automationid='MyControl']/element[2]/container[@automationid='root']/element[1]", 30000, null, "acf8a859-f326-486a-9816-ba6342af5630");
                _someelementInfo = new RepoItemInfo(this, "SomeElement", "container[@automationid='Root_Grid']/?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/element[@automationid='Loader']/?/?/container[@automationid='vbxMainBox']/?/?/container[@automationid='ispezioneView']//container[@automationid='MainGrid']//element[@automationid='teKm']/?/?/element[@automationid='PART_Root']/?/?/element[@automationid='borderContainer']/?/?/element[@automationid='PART_Content']/text[@automationid='PART_Editor']/?/?/container[@automationid='PART_ContentHost']/container[@automationid='Grid']/element[@automationid='PART_ScrollContentPresenter']/element[1]", 30000, null, "3bcb2478-8004-4430-85d1-700ed6355d47");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f08d598a-b0d6-49b3-ab4d-72f1eb766924")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f08d598a-b0d6-49b3-ab4d-72f1eb766924")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tile_Ispezione item.
            /// </summary>
            [RepositoryItem("acf8a859-f326-486a-9816-ba6342af5630")]
            public virtual Ranorex.Unknown Tile_Ispezione
            {
                get
                {
                    return _tile_ispezioneInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Tile_Ispezione item info.
            /// </summary>
            [RepositoryItemInfo("acf8a859-f326-486a-9816-ba6342af5630")]
            public virtual RepoItemInfo Tile_IspezioneInfo
            {
                get
                {
                    return _tile_ispezioneInfo;
                }
            }

            /// <summary>
            /// The SomeElement item.
            /// </summary>
            [RepositoryItem("3bcb2478-8004-4430-85d1-700ed6355d47")]
            public virtual Ranorex.Unknown SomeElement
            {
                get
                {
                    return _someelementInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement item info.
            /// </summary>
            [RepositoryItemInfo("3bcb2478-8004-4430-85d1-700ed6355d47")]
            public virtual RepoItemInfo SomeElementInfo
            {
                get
                {
                    return _someelementInfo;
                }
            }

            /// <summary>
            /// The Login folder.
            /// </summary>
            [RepositoryFolder("3c45b982-cb5f-4022-9f42-3eb8f97025c2")]
            public virtual G4_TEST_POST_RILASCIORepositoryFolders.LoginFolder Login
            {
                get { return _login; }
            }

            /// <summary>
            /// The DomandaRevisione folder.
            /// </summary>
            [RepositoryFolder("22e55e28-4eda-4b66-bb20-8d77fc255679")]
            public virtual G4_TEST_POST_RILASCIORepositoryFolders.DomandaRevisioneFolder DomandaRevisione
            {
                get { return _domandarevisione; }
            }

            /// <summary>
            /// The DatiRevisione folder.
            /// </summary>
            [RepositoryFolder("3d567730-7497-4b1f-a128-c65314a3314c")]
            public virtual G4_TEST_POST_RILASCIORepositoryFolders.DatiRevisioneFolder DatiRevisione
            {
                get { return _datirevisione; }
            }

            /// <summary>
            /// The RootGrid folder.
            /// </summary>
            [RepositoryFolder("6393cea5-0f9d-4e2a-8f01-e44abadef2aa")]
            public virtual G4_TEST_POST_RILASCIORepositoryFolders.RootGridFolder RootGrid
            {
                get { return _rootgrid; }
            }
        }

        /// <summary>
        /// The LoginFolder folder.
        /// </summary>
        [RepositoryFolder("3c45b982-cb5f-4022-9f42-3eb8f97025c2")]
        public partial class LoginFolder : RepoGenBaseFolder
        {
            RepoItemInfo _schermataloginInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _accediInfo;
            RepoItemInfo _datacontrollocreditoInfo;

            /// <summary>
            /// Creates a new Login  folder.
            /// </summary>
            public LoginFolder(RepoGenBaseFolder parentFolder) :
                    base("Login", "", parentFolder, 0, null, false, "3c45b982-cb5f-4022-9f42-3eb8f97025c2", "")
            {
                _schermataloginInfo = new RepoItemInfo(this, "SchermataLogin", "container[@automationid='Root_Grid']/element[@automationid='PART_WindowAdornerDecorator']/?/?/element[@automationid='PART_RootContentPresenter']/container//element[@automationid='PART_ContainerContent']/?/?/element[@automationid='contentPresenter']//text[@caption='Login']", 30000, null, "96d8afcd-8bff-4a82-8f81-108351cf61cd");
                _passwordInfo = new RepoItemInfo(this, "Password", "container[@automationid='Root_Grid']/element[@automationid='PART_WindowAdornerDecorator']/?/?/element[@automationid='PART_RootContentPresenter']//element[@automationid='PART_ContainerContent']/?/?/element[@automationid='contentPresenter']//element[@automationid='UtenteTextPwd']/?/?/element[@automationid='Border']/?/?/element[@automationid='borderContainer']//element[@automationid='PART_Content']/text[@automationid='PART_Editor']/element[@automationid='PART_ContentBorder']/container[@automationid='PART_ContentHost']/container[@automationid='Grid']/element[@automationid='PART_ScrollContentPresenter']/element[1]", 30000, null, "8a823c86-d783-4b8d-a4c2-6d5dda7394e1");
                _accediInfo = new RepoItemInfo(this, "Accedi", "container[@automationid='Root_Grid']/element[@automationid='PART_WindowAdornerDecorator']/?/?/element[@automationid='PART_RootContentPresenter']/?/?/element/container/element[@automationid='PART_ContainerContent']/?/?/element[@automationid='contentPresenter']/container//button[@automationid='AccediButton']/?/?/element[@automationid='Border']//element[@automationid='Content']/text[@caption='Accedi']", 30000, null, "c01eafa0-d2e1-413d-a96f-2dbcbb1e0bb7");
                _datacontrollocreditoInfo = new RepoItemInfo(this, "DataControlloCredito", "container[@automationid='Root_Grid']/?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/container/container[2]/element/container/container[3]/container[3]/container[3]/element[4]/container[@automationid='root']/element[@automationid='content']//text[@text~'^(\\d{2})\\/(\\d{2})\\/\\d{4} (\\d{2}):(\\d{2})$']", 30000, null, "35864f96-73dd-4c5c-b6b2-7d0154d8dcb2");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3c45b982-cb5f-4022-9f42-3eb8f97025c2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SchermataLogin item.
            /// </summary>
            [RepositoryItem("96d8afcd-8bff-4a82-8f81-108351cf61cd")]
            public virtual Ranorex.Text SchermataLogin
            {
                get
                {
                    return _schermataloginInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SchermataLogin item info.
            /// </summary>
            [RepositoryItemInfo("96d8afcd-8bff-4a82-8f81-108351cf61cd")]
            public virtual RepoItemInfo SchermataLoginInfo
            {
                get
                {
                    return _schermataloginInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("8a823c86-d783-4b8d-a4c2-6d5dda7394e1")]
            public virtual Ranorex.Unknown Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("8a823c86-d783-4b8d-a4c2-6d5dda7394e1")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Accedi item.
            /// </summary>
            [RepositoryItem("c01eafa0-d2e1-413d-a96f-2dbcbb1e0bb7")]
            public virtual Ranorex.Text Accedi
            {
                get
                {
                    return _accediInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Accedi item info.
            /// </summary>
            [RepositoryItemInfo("c01eafa0-d2e1-413d-a96f-2dbcbb1e0bb7")]
            public virtual RepoItemInfo AccediInfo
            {
                get
                {
                    return _accediInfo;
                }
            }

            /// <summary>
            /// The DataControlloCredito item.
            /// </summary>
            [RepositoryItem("35864f96-73dd-4c5c-b6b2-7d0154d8dcb2")]
            public virtual Ranorex.Text DataControlloCredito
            {
                get
                {
                    return _datacontrollocreditoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DataControlloCredito item info.
            /// </summary>
            [RepositoryItemInfo("35864f96-73dd-4c5c-b6b2-7d0154d8dcb2")]
            public virtual RepoItemInfo DataControlloCreditoInfo
            {
                get
                {
                    return _datacontrollocreditoInfo;
                }
            }
        }

        /// <summary>
        /// The DomandaRevisioneFolder folder.
        /// </summary>
        [RepositoryFolder("22e55e28-4eda-4b66-bb20-8d77fc255679")]
        public partial class DomandaRevisioneFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ispezione_stampadomanda_checktargaInfo;
            RepoItemInfo _ispezione_stampadomanda_formInfo;
            RepoItemInfo _ispezione_apridomandarevisioneInfo;

            /// <summary>
            /// Creates a new DomandaRevisione  folder.
            /// </summary>
            public DomandaRevisioneFolder(RepoGenBaseFolder parentFolder) :
                    base("DomandaRevisione", "", parentFolder, 0, null, false, "22e55e28-4eda-4b66-bb20-8d77fc255679", "")
            {
                _ispezione_stampadomanda_checktargaInfo = new RepoItemInfo(this, "Ispezione_StampaDomanda_CheckTarga", "container[@automationid='Root_Grid']/?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/container[@automationid='MainGrid']/element[@automationid='docAnteprima']//element[@automationid='backStageView']/?/?/container/element[@automationid='PART_ContentHost']/?/?/container[@automationid='PART_Root']/container[1]/container/element[@automationid='PART_Left']//list[@automationid='backstageViewItemsControl']/element[@automationid='itemsPresenter']/?/?/element[@automationid='Print']/?/?/container[@automationid='printGrid']/element[@automationid='documentViewer']/?/?/element[@automationid='documentPreviewDockLayoutManager']/element[6]/container/container/container/container[@automationid='AutoHideLayer']/element[@automationid='LayoutLayer']//container[@automationid='PART_Bounds']/?/?/element[@automationid='PART_Content']/?/?/list/?/?/container/element[@automationid='DocumentViewerPanel']//container/?/?/container/element[@automationid='PART_Content']/container/element/container//container[@automationid='documentPreviewScrollViewer']/?/?/element[@automationid='PART_ScrollContentPresenter']/element[@automationid='scrollablePageView']/element[@automationid='pageBorder']//container[@automationid='pageContentViewContainer']/container[1]//container[@caption='']/container[@caption='']/element[3]/container/element[14]//text[@caption~'^.{1,10}$']", 30000, null, "21d91442-479d-40dd-9220-bddd53a2decc");
                _ispezione_stampadomanda_formInfo = new RepoItemInfo(this, "Ispezione_StampaDomanda_Form", "container[@automationid='Root_Grid']/?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/container[@automationid='MainGrid']//container[@automationid='MyControl']", 30000, null, "e813b25c-9468-4f64-a4f3-3b20f8052bba");
                _ispezione_apridomandarevisioneInfo = new RepoItemInfo(this, "Ispezione_ApriDomandaRevisione", "container[@automationid='Root_Grid']/?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/element[@automationid='Loader']/?/?/container[@automationid='vbxMainBox']/?/?/container[@automationid='ispezioneView']//container[@automationid='MainGrid']/container[4]/list[@automationid='FlipView']/container[@automationid='Root']//container[@automationid='ScrollingHost']/?/?/container/element[@automationid='PART_ScrollContentPresenter']//element[@automationid='itemAccettazione']/container[@automationid='Root']/?/?/container[@automationid='ispezioneAccettazioneInvio']/?/?/element/container/container[@automationid='printDomandaRev']//button[@automationid='MyControl']/?/?/element[@automationid='Border']//text[@automationid='lblButtonText']", 30000, null, "c538a7fc-7f8d-41a2-bc29-6293ff003306");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("22e55e28-4eda-4b66-bb20-8d77fc255679")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Ispezione_StampaDomanda_CheckTarga item.
            /// </summary>
            [RepositoryItem("21d91442-479d-40dd-9220-bddd53a2decc")]
            public virtual Ranorex.Text Ispezione_StampaDomanda_CheckTarga
            {
                get
                {
                    return _ispezione_stampadomanda_checktargaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Ispezione_StampaDomanda_CheckTarga item info.
            /// </summary>
            [RepositoryItemInfo("21d91442-479d-40dd-9220-bddd53a2decc")]
            public virtual RepoItemInfo Ispezione_StampaDomanda_CheckTargaInfo
            {
                get
                {
                    return _ispezione_stampadomanda_checktargaInfo;
                }
            }

            /// <summary>
            /// The Ispezione_StampaDomanda_Form item.
            /// </summary>
            [RepositoryItem("e813b25c-9468-4f64-a4f3-3b20f8052bba")]
            public virtual Ranorex.Container Ispezione_StampaDomanda_Form
            {
                get
                {
                    return _ispezione_stampadomanda_formInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Ispezione_StampaDomanda_Form item info.
            /// </summary>
            [RepositoryItemInfo("e813b25c-9468-4f64-a4f3-3b20f8052bba")]
            public virtual RepoItemInfo Ispezione_StampaDomanda_FormInfo
            {
                get
                {
                    return _ispezione_stampadomanda_formInfo;
                }
            }

            /// <summary>
            /// The Ispezione_ApriDomandaRevisione item.
            /// </summary>
            [RepositoryItem("c538a7fc-7f8d-41a2-bc29-6293ff003306")]
            public virtual Ranorex.Text Ispezione_ApriDomandaRevisione
            {
                get
                {
                    return _ispezione_apridomandarevisioneInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Ispezione_ApriDomandaRevisione item info.
            /// </summary>
            [RepositoryItemInfo("c538a7fc-7f8d-41a2-bc29-6293ff003306")]
            public virtual RepoItemInfo Ispezione_ApriDomandaRevisioneInfo
            {
                get
                {
                    return _ispezione_apridomandarevisioneInfo;
                }
            }
        }

        /// <summary>
        /// The DatiRevisioneFolder folder.
        /// </summary>
        [RepositoryFolder("3d567730-7497-4b1f-a128-c65314a3314c")]
        public partial class DatiRevisioneFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ispezione_kilometriInfo;
            RepoItemInfo _btnproprietarioInfo;
            RepoItemInfo _btnaccettazioneInfo;
            RepoItemInfo _ispezione_salvaaccettazioneInfo;
            RepoItemInfo _ispezione_accettazioneeffettuataInfo;

            /// <summary>
            /// Creates a new DatiRevisione  folder.
            /// </summary>
            public DatiRevisioneFolder(RepoGenBaseFolder parentFolder) :
                    base("DatiRevisione", "", parentFolder, 0, null, false, "3d567730-7497-4b1f-a128-c65314a3314c", "")
            {
                _ispezione_kilometriInfo = new RepoItemInfo(this, "Ispezione_KILOMETRI", "container[@automationid='Root_Grid']/?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/element[@automationid='Loader']/?/?/container[@automationid='vbxMainBox']/?/?/container[@automationid='ispezioneView']/element//container[@automationid='MainGrid']/container[2]/element/container/container[1]/element[@automationid='teKm']/?/?/element[@automationid='PART_Root']/container/element[1]", 30000, null, "f4b753fe-e3a0-481c-8f29-2b03a135d6b8");
                _btnproprietarioInfo = new RepoItemInfo(this, "BtnProprietario", "container[@automationid='Root_Grid']/?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/element[@automationid='Loader']/?/?/container[@automationid='vbxMainBox']/?/?/container[@automationid='ispezioneView']//container[@automationid='MainGrid']/container[3]/?/?/radiobutton[@automationid='btnProprietario']", 30000, null, "a28952c4-4bf3-4d0a-ac3c-e57e4e6fa313");
                _btnaccettazioneInfo = new RepoItemInfo(this, "BtnAccettazione", "container[@automationid='Root_Grid']/?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/element[@automationid='Loader']/?/?/container[@automationid='vbxMainBox']/?/?/container[@automationid='ispezioneView']//container[@automationid='MainGrid']/container[3]/?/?/radiobutton[@automationid='btnAccettazione']", 30000, null, "f263b1fa-c340-405a-923f-38938457a657");
                _ispezione_salvaaccettazioneInfo = new RepoItemInfo(this, "Ispezione_SalvaAccettazione", "container[@automationid='Root_Grid']/?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/element[@automationid='Loader']/?/?/container[@automationid='vbxMainBox']/?/?/container[@automationid='ispezioneView']//container[@automationid='MainGrid']/container[4]/list[@automationid='FlipView']/container[@automationid='Root']//container[@automationid='ScrollingHost']//element[@automationid='PART_ScrollContentPresenter']//element[@automationid='itemAccettazione']/container[@automationid='Root']/?/?/container[@automationid='ispezioneAccettazioneInvio']/?/?/element/container/container[2]/container[@automationid='btnSave']//button[@automationid='MyControl']/?/?/element[@automationid='Border']//text[@automationid='lblButtonText']", 30000, null, "751499e9-7f2f-4a29-8e3d-da82d49e8fa3");
                _ispezione_accettazioneeffettuataInfo = new RepoItemInfo(this, "Ispezione_AccettazioneEffettuata", "container[@automationid='Root_Grid']/?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/element[@automationid='Loader']/?/?/container[@automationid='vbxMainBox']/?/?/container[@automationid='ispezioneView']//container[@automationid='MainGrid']/container[4]/list[@automationid='FlipView']/container[@automationid='Root']/element[1]/container/container[@automationid='ScrollingHost']//element[@automationid='PART_ScrollContentPresenter']//element[@automationid='itemAccettazione']/container[@automationid='Root']/?/?/container[@automationid='ispezioneAccettazioneInvio']/?/?/element/container/container[2]/container[3]//text[@caption='Accettazione effettuata']/?/?/element[@automationid='Content']/text[@caption='Accettazione effettuata']", 30000, null, "95e762ec-3a5c-42d3-9b3f-3560b2f2f9cc");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3d567730-7497-4b1f-a128-c65314a3314c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Ispezione_KILOMETRI item.
            /// </summary>
            [RepositoryItem("f4b753fe-e3a0-481c-8f29-2b03a135d6b8")]
            public virtual Ranorex.Unknown Ispezione_KILOMETRI
            {
                get
                {
                    return _ispezione_kilometriInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Ispezione_KILOMETRI item info.
            /// </summary>
            [RepositoryItemInfo("f4b753fe-e3a0-481c-8f29-2b03a135d6b8")]
            public virtual RepoItemInfo Ispezione_KILOMETRIInfo
            {
                get
                {
                    return _ispezione_kilometriInfo;
                }
            }

            /// <summary>
            /// The BtnProprietario item.
            /// </summary>
            [RepositoryItem("a28952c4-4bf3-4d0a-ac3c-e57e4e6fa313")]
            public virtual Ranorex.RadioButton BtnProprietario
            {
                get
                {
                    return _btnproprietarioInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The BtnProprietario item info.
            /// </summary>
            [RepositoryItemInfo("a28952c4-4bf3-4d0a-ac3c-e57e4e6fa313")]
            public virtual RepoItemInfo BtnProprietarioInfo
            {
                get
                {
                    return _btnproprietarioInfo;
                }
            }

            /// <summary>
            /// The BtnAccettazione item.
            /// </summary>
            [RepositoryItem("f263b1fa-c340-405a-923f-38938457a657")]
            public virtual Ranorex.RadioButton BtnAccettazione
            {
                get
                {
                    return _btnaccettazioneInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The BtnAccettazione item info.
            /// </summary>
            [RepositoryItemInfo("f263b1fa-c340-405a-923f-38938457a657")]
            public virtual RepoItemInfo BtnAccettazioneInfo
            {
                get
                {
                    return _btnaccettazioneInfo;
                }
            }

            /// <summary>
            /// The Ispezione_SalvaAccettazione item.
            /// </summary>
            [RepositoryItem("751499e9-7f2f-4a29-8e3d-da82d49e8fa3")]
            public virtual Ranorex.Text Ispezione_SalvaAccettazione
            {
                get
                {
                    return _ispezione_salvaaccettazioneInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Ispezione_SalvaAccettazione item info.
            /// </summary>
            [RepositoryItemInfo("751499e9-7f2f-4a29-8e3d-da82d49e8fa3")]
            public virtual RepoItemInfo Ispezione_SalvaAccettazioneInfo
            {
                get
                {
                    return _ispezione_salvaaccettazioneInfo;
                }
            }

            /// <summary>
            /// The Ispezione_AccettazioneEffettuata item.
            /// </summary>
            [RepositoryItem("95e762ec-3a5c-42d3-9b3f-3560b2f2f9cc")]
            public virtual Ranorex.Text Ispezione_AccettazioneEffettuata
            {
                get
                {
                    return _ispezione_accettazioneeffettuataInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Ispezione_AccettazioneEffettuata item info.
            /// </summary>
            [RepositoryItemInfo("95e762ec-3a5c-42d3-9b3f-3560b2f2f9cc")]
            public virtual RepoItemInfo Ispezione_AccettazioneEffettuataInfo
            {
                get
                {
                    return _ispezione_accettazioneeffettuataInfo;
                }
            }
        }

        /// <summary>
        /// The RootGridFolder folder.
        /// </summary>
        [RepositoryFolder("6393cea5-0f9d-4e2a-8f01-e44abadef2aa")]
        public partial class RootGridFolder : RepoGenBaseFolder
        {
            RepoItemInfo _msgbx_annullamentomodificheInfo;
            RepoItemInfo _ispezione_nuovoinserimentoInfo;
            RepoItemInfo _msgbx_annullamentomodifche_yesInfo;
            RepoItemInfo _ispezione_inviapcstazioneInfo;
            RepoItemInfo _ispezione_datiidentificativi_catveicoloInfo;
            RepoItemInfo _ispezione_datiidentificativi_cicInfo;
            RepoItemInfo _ispezione_datiidentificativi_targaInfo;
            RepoItemInfo _ispezione_datiidentificativi_telaioInfo;
            RepoItemInfo _ispezione_datiidentificativi_kmInfo;
            RepoItemInfo _vbxmainboxInfo;

            /// <summary>
            /// Creates a new RootGrid  folder.
            /// </summary>
            public RootGridFolder(RepoGenBaseFolder parentFolder) :
                    base("RootGrid", "container[@automationid='Root_Grid']", parentFolder, 30000, null, false, "6393cea5-0f9d-4e2a-8f01-e44abadef2aa", "")
            {
                _msgbx_annullamentomodificheInfo = new RepoItemInfo(this, "msgbx_AnnullamentoModifiche", "?/?/element[@automationid='PART_WindowAdornerDecorator']/element[2]/?/?/container/element/element/element/element/element/container/container/text[@caption='Annullamento modifiche']", 30000, null, "305bd284-16b4-4543-a5e1-2cdc0d2aa37a");
                _ispezione_nuovoinserimentoInfo = new RepoItemInfo(this, "Ispezione_NuovoInserimento", "?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/element[@automationid='Loader']/?/?/container[@automationid='vbxMainBox']/?/?/container[@automationid='ispezioneView']//container[@automationid='MainGrid']/container[1]/?/?/container[@automationid='btnClean']/element", 30000, null, "d7393838-cdaa-441e-b571-00ae6ce66cbe");
                _msgbx_annullamentomodifche_yesInfo = new RepoItemInfo(this, "msgbx_AnnullamentoModifche_yes", "element/element[@automationid='PART_WindowAdornerDecorator']/element[2]/element[3]/container/element/element/element/element/element/container/container/container[2]/container[@automationid='yesNoGrid']/button[@automationid='PART_YesButton']", 30000, null, "d935443b-5516-4ea5-b876-c6d6b1608b53");
                _ispezione_inviapcstazioneInfo = new RepoItemInfo(this, "Ispezione_InviaPCStazione", "?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/element[@automationid='Loader']/?/?/container[@automationid='vbxMainBox']/?/?/container[@automationid='ispezioneView']//container[@automationid='MainGrid']/container[4]/list[@automationid='FlipView']/container[@automationid='Root']//container[@automationid='ScrollingHost']/?/?/container/element[@automationid='PART_ScrollContentPresenter']//element[@automationid='itemAccettazione']/container[@automationid='Root']/?/?/container[@automationid='ispezioneAccettazioneInvio']/?/?/element/container/container[@automationid='inviaPCStaz']//button[@automationid='MyControl']/?/?/element[@automationid='Border']//text[@automationid='lblButtonText']", 30000, null, "73c4ce05-2305-421f-b318-20b395e3af67");
                _ispezione_datiidentificativi_catveicoloInfo = new RepoItemInfo(this, "Ispezione_DatiIdentificativi_CatVeicolo", "?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/element[@automationid='Loader']/?/?/container[@automationid='vbxMainBox']/?/?/container[@automationid='ispezioneView']//container[@automationid='MainGrid']/container[2]/element/container/container[1]/element[1]", 30000, null, "b7543385-b3c5-4122-9c0b-415e837b6348");
                _ispezione_datiidentificativi_cicInfo = new RepoItemInfo(this, "Ispezione_DatiIdentificativi_CIC", "?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/element[@automationid='Loader']/?/?/container[@automationid='vbxMainBox']/?/?/container[@automationid='ispezioneView']//container[@automationid='MainGrid']/container[2]/element/container/container[1]/element[@automationid='CICTextEdit']", 30000, null, "d45f3e42-de45-416d-b8de-ae05934f9524");
                _ispezione_datiidentificativi_targaInfo = new RepoItemInfo(this, "Ispezione_DatiIdentificativi_TARGA", "?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/element[@automationid='Loader']/?/?/container[@automationid='vbxMainBox']/?/?/container[@automationid='ispezioneView']/element//container[@automationid='MainGrid']/container[2]/element/container/container[1]/element[@automationid='Targa']/?/?/element[@automationid='PART_Root']/container/element[1]", 30000, null, "3f3a5965-9408-4c9f-bbe4-40c07e74336c");
                _ispezione_datiidentificativi_telaioInfo = new RepoItemInfo(this, "Ispezione_DatiIdentificativi_Telaio", "?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/element[@automationid='Loader']/?/?/container[@automationid='vbxMainBox']/?/?/container[@automationid='ispezioneView']//container[@automationid='MainGrid']/container[2]/element/container/container[1]/element[@automationid='Telaio']", 30000, null, "ceee4f54-e4bc-4feb-b7af-9cb6319ab218");
                _ispezione_datiidentificativi_kmInfo = new RepoItemInfo(this, "Ispezione_DatiIdentificativi_Km", "?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']/element[@automationid='Loader']/?/?/container[@automationid='vbxMainBox']/?/?/container[@automationid='ispezioneView']//container[@automationid='MainGrid']/container[2]/element/container/container[1]/element[@automationid='teKm']", 30000, null, "2adecd4e-ce74-46be-b8ba-7d364987ab11");
                _vbxmainboxInfo = new RepoItemInfo(this, "VbxMainBox", "?/?/element[@automationid='PART_WindowAdornerDecorator']/element[@automationid='PART_RootContentPresenter']/?/?/element[@automationid='FloatingContainerBorder']/?/?/element[@automationid='FloatingContainerBody']/?/?/element[@automationid='PART_ContainerContent']//element[@automationid='contentPresenter']//container[@automationid='vbxMainBox']", 30000, null, "142fc504-d225-43e3-ad86-0c6a431c9806");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6393cea5-0f9d-4e2a-8f01-e44abadef2aa")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6393cea5-0f9d-4e2a-8f01-e44abadef2aa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The msgbx_AnnullamentoModifiche item.
            /// </summary>
            [RepositoryItem("305bd284-16b4-4543-a5e1-2cdc0d2aa37a")]
            public virtual Ranorex.Text msgbx_AnnullamentoModifiche
            {
                get
                {
                    return _msgbx_annullamentomodificheInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The msgbx_AnnullamentoModifiche item info.
            /// </summary>
            [RepositoryItemInfo("305bd284-16b4-4543-a5e1-2cdc0d2aa37a")]
            public virtual RepoItemInfo msgbx_AnnullamentoModificheInfo
            {
                get
                {
                    return _msgbx_annullamentomodificheInfo;
                }
            }

            /// <summary>
            /// The Ispezione_NuovoInserimento item.
            /// </summary>
            [RepositoryItem("d7393838-cdaa-441e-b571-00ae6ce66cbe")]
            public virtual Ranorex.Unknown Ispezione_NuovoInserimento
            {
                get
                {
                    return _ispezione_nuovoinserimentoInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Ispezione_NuovoInserimento item info.
            /// </summary>
            [RepositoryItemInfo("d7393838-cdaa-441e-b571-00ae6ce66cbe")]
            public virtual RepoItemInfo Ispezione_NuovoInserimentoInfo
            {
                get
                {
                    return _ispezione_nuovoinserimentoInfo;
                }
            }

            /// <summary>
            /// The msgbx_AnnullamentoModifche_yes item.
            /// </summary>
            [RepositoryItem("d935443b-5516-4ea5-b876-c6d6b1608b53")]
            public virtual Ranorex.Button msgbx_AnnullamentoModifche_yes
            {
                get
                {
                    return _msgbx_annullamentomodifche_yesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The msgbx_AnnullamentoModifche_yes item info.
            /// </summary>
            [RepositoryItemInfo("d935443b-5516-4ea5-b876-c6d6b1608b53")]
            public virtual RepoItemInfo msgbx_AnnullamentoModifche_yesInfo
            {
                get
                {
                    return _msgbx_annullamentomodifche_yesInfo;
                }
            }

            /// <summary>
            /// The Ispezione_InviaPCStazione item.
            /// </summary>
            [RepositoryItem("73c4ce05-2305-421f-b318-20b395e3af67")]
            public virtual Ranorex.Text Ispezione_InviaPCStazione
            {
                get
                {
                    return _ispezione_inviapcstazioneInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Ispezione_InviaPCStazione item info.
            /// </summary>
            [RepositoryItemInfo("73c4ce05-2305-421f-b318-20b395e3af67")]
            public virtual RepoItemInfo Ispezione_InviaPCStazioneInfo
            {
                get
                {
                    return _ispezione_inviapcstazioneInfo;
                }
            }

            /// <summary>
            /// The Ispezione_DatiIdentificativi_CatVeicolo item.
            /// </summary>
            [RepositoryItem("b7543385-b3c5-4122-9c0b-415e837b6348")]
            public virtual Ranorex.Unknown Ispezione_DatiIdentificativi_CatVeicolo
            {
                get
                {
                    return _ispezione_datiidentificativi_catveicoloInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Ispezione_DatiIdentificativi_CatVeicolo item info.
            /// </summary>
            [RepositoryItemInfo("b7543385-b3c5-4122-9c0b-415e837b6348")]
            public virtual RepoItemInfo Ispezione_DatiIdentificativi_CatVeicoloInfo
            {
                get
                {
                    return _ispezione_datiidentificativi_catveicoloInfo;
                }
            }

            /// <summary>
            /// The Ispezione_DatiIdentificativi_CIC item.
            /// </summary>
            [RepositoryItem("d45f3e42-de45-416d-b8de-ae05934f9524")]
            public virtual Ranorex.Unknown Ispezione_DatiIdentificativi_CIC
            {
                get
                {
                    return _ispezione_datiidentificativi_cicInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Ispezione_DatiIdentificativi_CIC item info.
            /// </summary>
            [RepositoryItemInfo("d45f3e42-de45-416d-b8de-ae05934f9524")]
            public virtual RepoItemInfo Ispezione_DatiIdentificativi_CICInfo
            {
                get
                {
                    return _ispezione_datiidentificativi_cicInfo;
                }
            }

            /// <summary>
            /// The Ispezione_DatiIdentificativi_TARGA item.
            /// </summary>
            [RepositoryItem("3f3a5965-9408-4c9f-bbe4-40c07e74336c")]
            public virtual Ranorex.Unknown Ispezione_DatiIdentificativi_TARGA
            {
                get
                {
                    return _ispezione_datiidentificativi_targaInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Ispezione_DatiIdentificativi_TARGA item info.
            /// </summary>
            [RepositoryItemInfo("3f3a5965-9408-4c9f-bbe4-40c07e74336c")]
            public virtual RepoItemInfo Ispezione_DatiIdentificativi_TARGAInfo
            {
                get
                {
                    return _ispezione_datiidentificativi_targaInfo;
                }
            }

            /// <summary>
            /// The Ispezione_DatiIdentificativi_Telaio item.
            /// </summary>
            [RepositoryItem("ceee4f54-e4bc-4feb-b7af-9cb6319ab218")]
            public virtual Ranorex.Unknown Ispezione_DatiIdentificativi_Telaio
            {
                get
                {
                    return _ispezione_datiidentificativi_telaioInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Ispezione_DatiIdentificativi_Telaio item info.
            /// </summary>
            [RepositoryItemInfo("ceee4f54-e4bc-4feb-b7af-9cb6319ab218")]
            public virtual RepoItemInfo Ispezione_DatiIdentificativi_TelaioInfo
            {
                get
                {
                    return _ispezione_datiidentificativi_telaioInfo;
                }
            }

            /// <summary>
            /// The Ispezione_DatiIdentificativi_Km item.
            /// </summary>
            [RepositoryItem("2adecd4e-ce74-46be-b8ba-7d364987ab11")]
            public virtual Ranorex.Unknown Ispezione_DatiIdentificativi_Km
            {
                get
                {
                    return _ispezione_datiidentificativi_kmInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Ispezione_DatiIdentificativi_Km item info.
            /// </summary>
            [RepositoryItemInfo("2adecd4e-ce74-46be-b8ba-7d364987ab11")]
            public virtual RepoItemInfo Ispezione_DatiIdentificativi_KmInfo
            {
                get
                {
                    return _ispezione_datiidentificativi_kmInfo;
                }
            }

            /// <summary>
            /// The VbxMainBox item.
            /// </summary>
            [RepositoryItem("142fc504-d225-43e3-ad86-0c6a431c9806")]
            public virtual Ranorex.Container VbxMainBox
            {
                get
                {
                    return _vbxmainboxInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The VbxMainBox item info.
            /// </summary>
            [RepositoryItemInfo("142fc504-d225-43e3-ad86-0c6a431c9806")]
            public virtual RepoItemInfo VbxMainBoxInfo
            {
                get
                {
                    return _vbxmainboxInfo;
                }
            }
        }

        /// <summary>
        /// The ChiusuraFolder folder.
        /// </summary>
        [RepositoryFolder("157c1c07-a34e-4690-8b91-97412284a983")]
        public partial class ChiusuraFolder : RepoGenBaseFolder
        {
            RepoItemInfo _chiudig4Info;
            RepoItemInfo _confermachiusura_msgbxInfo;
            RepoItemInfo _confermachiusura_msgbx_okInfo;

            /// <summary>
            /// Creates a new Chiusura  folder.
            /// </summary>
            public ChiusuraFolder(RepoGenBaseFolder parentFolder) :
                    base("Chiusura", "", parentFolder, 0, null, false, "157c1c07-a34e-4690-8b91-97412284a983", "")
            {
                _chiudig4Info = new RepoItemInfo(this, "ChiudiG4", "/form[@processname='GesRevNET4']/container[@automationid='Root_Grid']//element[@automationid='PART_RootContentPresenter']//element[@automationid='PART_Header']/?/?/container[@automationid='stackPanel']/button[@automationid='PART_CloseButton']/container[@automationid='Button']/element[@automationid='PressedState']", 30000, null, "d8fa9a37-41eb-4844-8ff8-eaf661e3c823");
                _confermachiusura_msgbxInfo = new RepoItemInfo(this, "ConfermaChiusura_MsgBx", "/form[@processname='GesRevNET4']/element/element/element[1]/element//container", 30000, null, "c4614456-a310-44be-9cf6-1be4e11f0b63");
                _confermachiusura_msgbx_okInfo = new RepoItemInfo(this, "ConfermaChiusura_MsgBx_Ok", "/form[@processname='GesRevNET4']/element//container/container/container[2]/container[@automationid='yesNoGrid']/button[@automationid='PART_YesButton']/element[@automationid='border']", 30000, null, "eab3eb4b-446b-438b-8c4f-ada2b12eb46e");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("157c1c07-a34e-4690-8b91-97412284a983")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ChiudiG4 item.
            /// </summary>
            [RepositoryItem("d8fa9a37-41eb-4844-8ff8-eaf661e3c823")]
            public virtual Ranorex.Unknown ChiudiG4
            {
                get
                {
                    return _chiudig4Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ChiudiG4 item info.
            /// </summary>
            [RepositoryItemInfo("d8fa9a37-41eb-4844-8ff8-eaf661e3c823")]
            public virtual RepoItemInfo ChiudiG4Info
            {
                get
                {
                    return _chiudig4Info;
                }
            }

            /// <summary>
            /// The ConfermaChiusura_MsgBx item.
            /// </summary>
            [RepositoryItem("c4614456-a310-44be-9cf6-1be4e11f0b63")]
            public virtual Ranorex.Container ConfermaChiusura_MsgBx
            {
                get
                {
                    return _confermachiusura_msgbxInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ConfermaChiusura_MsgBx item info.
            /// </summary>
            [RepositoryItemInfo("c4614456-a310-44be-9cf6-1be4e11f0b63")]
            public virtual RepoItemInfo ConfermaChiusura_MsgBxInfo
            {
                get
                {
                    return _confermachiusura_msgbxInfo;
                }
            }

            /// <summary>
            /// The ConfermaChiusura_MsgBx_Ok item.
            /// </summary>
            [RepositoryItem("eab3eb4b-446b-438b-8c4f-ada2b12eb46e")]
            public virtual Ranorex.Unknown ConfermaChiusura_MsgBx_Ok
            {
                get
                {
                    return _confermachiusura_msgbx_okInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ConfermaChiusura_MsgBx_Ok item info.
            /// </summary>
            [RepositoryItemInfo("eab3eb4b-446b-438b-8c4f-ada2b12eb46e")]
            public virtual RepoItemInfo ConfermaChiusura_MsgBx_OkInfo
            {
                get
                {
                    return _confermachiusura_msgbx_okInfo;
                }
            }
        }

        /// <summary>
        /// The ProxyAppFolder folder.
        /// </summary>
        [RepositoryFolder("483a9e99-428c-46a9-9492-66d0bb3b1373")]
        public partial class ProxyAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _chiudiInfo;
            RepoItemInfo _riduciaiconaInfo;

            /// <summary>
            /// Creates a new Proxy  folder.
            /// </summary>
            public ProxyAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Proxy", "/form[@title='MainWindow']", parentFolder, 30000, null, true, "483a9e99-428c-46a9-9492-66d0bb3b1373", "")
            {
                _chiudiInfo = new RepoItemInfo(this, "Chiudi", "?/?/button[@accessiblename='Chiudi']", 30000, null, "46b0dd47-5b01-4c6c-9b92-362ba2e97915");
                _riduciaiconaInfo = new RepoItemInfo(this, "RiduciAIcona", "?/?/button[@accessiblename='Riduci a icona']", 30000, null, "a8834d52-0cb1-4cc8-8bbc-9be795c85388");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("483a9e99-428c-46a9-9492-66d0bb3b1373")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("483a9e99-428c-46a9-9492-66d0bb3b1373")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Chiudi item.
            /// </summary>
            [RepositoryItem("46b0dd47-5b01-4c6c-9b92-362ba2e97915")]
            public virtual Ranorex.Button Chiudi
            {
                get
                {
                    return _chiudiInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Chiudi item info.
            /// </summary>
            [RepositoryItemInfo("46b0dd47-5b01-4c6c-9b92-362ba2e97915")]
            public virtual RepoItemInfo ChiudiInfo
            {
                get
                {
                    return _chiudiInfo;
                }
            }

            /// <summary>
            /// The RiduciAIcona item.
            /// </summary>
            [RepositoryItem("a8834d52-0cb1-4cc8-8bbc-9be795c85388")]
            public virtual Ranorex.Button RiduciAIcona
            {
                get
                {
                    return _riduciaiconaInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RiduciAIcona item info.
            /// </summary>
            [RepositoryItemInfo("a8834d52-0cb1-4cc8-8bbc-9be795c85388")]
            public virtual RepoItemInfo RiduciAIconaInfo
            {
                get
                {
                    return _riduciaiconaInfo;
                }
            }
        }

        /// <summary>
        /// The BackUpAppFolder folder.
        /// </summary>
        [RepositoryFolder("01fc1f17-086d-49bc-ae9b-850c5873a6c4")]
        public partial class BackUpAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _chiudibackupInfo;

            /// <summary>
            /// Creates a new BackUp  folder.
            /// </summary>
            public BackUpAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BackUp", "/form[@automationid='mainWindow']", parentFolder, 30000, null, true, "01fc1f17-086d-49bc-ae9b-850c5873a6c4", "")
            {
                _chiudibackupInfo = new RepoItemInfo(this, "ChiudiBackUp", "container/container//button[@text='x']/element", 30000, null, "d4bf2842-da06-4129-9383-d7e2ca011ad4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("01fc1f17-086d-49bc-ae9b-850c5873a6c4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("01fc1f17-086d-49bc-ae9b-850c5873a6c4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ChiudiBackUp item.
            /// </summary>
            [RepositoryItem("d4bf2842-da06-4129-9383-d7e2ca011ad4")]
            public virtual Ranorex.Unknown ChiudiBackUp
            {
                get
                {
                    return _chiudibackupInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ChiudiBackUp item info.
            /// </summary>
            [RepositoryItemInfo("d4bf2842-da06-4129-9383-d7e2ca011ad4")]
            public virtual RepoItemInfo ChiudiBackUpInfo
            {
                get
                {
                    return _chiudibackupInfo;
                }
            }
        }

        /// <summary>
        /// The GesRevNET4AppFolder folder.
        /// </summary>
        [RepositoryFolder("e30b364a-e253-4aa6-9d8e-adfb3136766b")]
        public partial class GesRevNET4AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _someelementInfo;
            RepoItemInfo _someelement1Info;

            /// <summary>
            /// Creates a new GesRevNET4  folder.
            /// </summary>
            public GesRevNET4AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GesRevNET4", "/contextmenu[@processname='GesRevNET4']", parentFolder, 30000, null, false, "e30b364a-e253-4aa6-9d8e-adfb3136766b", "")
            {
                _someelementInfo = new RepoItemInfo(this, "SomeElement", ".//container[@automationid='Root']/element[@automationid='PART_Border']/element[@automationid='PART_ContentPresenter']//element[@automationid='Content']//element[@automationid='PART_GridControl']/element[6]//element[@automationid='PART_ThemesLoader']/element[@automationid='border1']/element[@automationid='border2']//container[@automationid='scr']/?/?/container[@automationid='rowPresenterGrid']/container[1]/element[@automationid='PART_ScrollContentPresenter']/element[@automationid='dataPresenter']/element[@automationid='PART_DataPresenterBackground']/container/element[2]/container/element[6]/?/?/container[@automationid='PART_LayoutPanel']/element[3]/container/element[1]/element", 30000, null, "c2d4d256-2a62-4798-9d51-b0f53e9a913d");
                _someelement1Info = new RepoItemInfo(this, "SomeElement1", ".//container[@automationid='Root']/element[@automationid='PART_Border']/element[@automationid='PART_ContentPresenter']//element[@automationid='Content']//element[@automationid='PART_GridControl']/element[6]//element[@automationid='PART_ThemesLoader']/element[@automationid='border1']/element[@automationid='border2']//container[@automationid='scr']/?/?/container[@automationid='rowPresenterGrid']/container[1]/element[@automationid='PART_ScrollContentPresenter']/element[@automationid='dataPresenter']/element[@automationid='PART_DataPresenterBackground']/container/element[2]/container/element[4]/?/?/container[@automationid='PART_LayoutPanel']/element[3]/container/element[1]/element", 30000, null, "2a02030d-fe4f-469e-b789-cf3f3469b920");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e30b364a-e253-4aa6-9d8e-adfb3136766b")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e30b364a-e253-4aa6-9d8e-adfb3136766b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeElement item.
            /// </summary>
            [RepositoryItem("c2d4d256-2a62-4798-9d51-b0f53e9a913d")]
            public virtual Ranorex.Unknown SomeElement
            {
                get
                {
                    return _someelementInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement item info.
            /// </summary>
            [RepositoryItemInfo("c2d4d256-2a62-4798-9d51-b0f53e9a913d")]
            public virtual RepoItemInfo SomeElementInfo
            {
                get
                {
                    return _someelementInfo;
                }
            }

            /// <summary>
            /// The SomeElement1 item.
            /// </summary>
            [RepositoryItem("2a02030d-fe4f-469e-b789-cf3f3469b920")]
            public virtual Ranorex.Unknown SomeElement1
            {
                get
                {
                    return _someelement1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement1 item info.
            /// </summary>
            [RepositoryItemInfo("2a02030d-fe4f-469e-b789-cf3f3469b920")]
            public virtual RepoItemInfo SomeElement1Info
            {
                get
                {
                    return _someelement1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
